### ISSUE TITLE
运行cli_demo.py报错：RuntimeError: [1] is setting up NCCL communicator

### ISSUE THREAD

**Issue by cy7022** [THUDM/CogVLM#104]
使用的服务器是 2 * RTX 3090(24G)
请问如何解决这个错误？感谢！
```
log:
(vlm) root@b8d2fd0761a7:~/CogVLM# torchrun --standalone --nnodes=1 --nproc-per-node=2 cli_demo.py --from_pretrained cogvlm-grounding-generalist --version base --english --bf16
[2023-11-18 22:31:19,977] torch.distributed.run: [WARNING] master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
[2023-11-18 22:31:19,977] torch.distributed.run: [WARNING]
[2023-11-18 22:31:19,977] torch.distributed.run: [WARNING] *****************************************
[2023-11-18 22:31:19,977] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each      process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal      performance in your application as needed.
[2023-11-18 22:31:19,977] torch.distributed.run: [WARNING] *****************************************
[2023-11-18 22:31:24,016] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-11-18 22:31:24,120] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/opt/conda/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
/opt/conda/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
[2023-11-18 22:31:26,491] [INFO] building CogVLMModel model ...
[2023-11-18 22:31:26,553] [INFO] building CogVLMModel model ...
[2023-11-18 22:31:27,987] [INFO] [RANK 0] > initializing model parallel with size 2
[2023-11-18 22:31:27,988] [INFO] [RANK 0] You are using model-only mode.
For torch.distributed users or loading model parallel models, set environment variables RANK, WORLD_SIZE and LOCAL_RANK.
[2023-11-18 22:31:43,566] [INFO] [RANK 0]  > number of parameters on model parallel rank 0: 8893252992
[2023-11-18 22:31:45,691] [INFO] [RANK 1]  > number of parameters on model parallel rank 1: 8893252992
[2023-11-18 22:31:52,379] [INFO] [RANK 0] > initializing model parallel with size 1
[2023-11-18 22:31:52,382] [INFO] [RANK 0] building CogVLMModel model ...
[2023-11-18 22:32:05,204] [INFO] [RANK 0]  > number of parameters on model parallel rank 0: 17639685376
[2023-11-18 22:32:16,001] [INFO] [RANK 0] global rank 0 is loading checkpoint /root/siton-tmp/cogvlm-grounding-generalist/1/mp_rank_00_model_states.pt
Traceback (most recent call last):
  File "/root/CogVLM/cli_demo.py", line 154, in <module>
    main()
  File "/root/CogVLM/cli_demo.py", line 34, in main
    model, model_args = CogVLMModel.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/sat/model/base_model.py", line 232, in from_pretrained
    torch.distributed.barrier()
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3696, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: [1] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Connection reset by peer. This may indicate a possible application crash on rank 0 or a network set up issue.
[2023-11-18 22:34:20,458] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -9) local_rank: 0 (pid: 327) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
cli_demo.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-11-18_22:34:20
  host      : b8d2fd0761a7
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 328)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-18_22:34:20
  host      : b8d2fd0761a7
  rank      : 0 (local_rank: 0)
  exitcode  : -9 (pid: 327)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 327
============================================================
```
—————————————————————————————————————————————————————

**Comment by 1049451037** [comment]
`RuntimeError: [1] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Connection reset by peer. This may indicate a possible application crash on rank 0 or a network set up issue.`

看起来是你的nccl配置有问题

**Comment by jsxapril** [comment]
请问这个问题解决了吗？用之前的chat模型没有这个问题，但突然导入部分卡死状态，然后看新上传模型chat-v1.1是分开多个部分的想着实验一下能不能解决卡死问题，结果又出现这个问题，看报错在rank0没有找到latest文件，应该是模型包装方式更新了，但代码没更新导入参数方式。实在崩溃。不知道如何修改这部分问题？谢谢
4*V100(32G),其他配置参数和需求一致。

**Comment by 1049451037** [comment]
huggingface的版本不是sat的代码可以加载的，huggingface的模型只能huggingface来加载。

**Comment by 1049451037** [comment]
能用sat加载的模型我正在上传huggingface和modelscope。

**Comment by 1049451037** [comment]
https://huggingface.co/THUDM/cogvlm-chat-hf/discussions/2#655ccd16605e1e91fb226cd8

huggingface的版本也支持多卡运行了，可以试一下～

**Comment by elesun2018** [comment]
# torchrun --standalone --nnodes=1 --nproc-per-node=2 cli_demo.py --from_pretrained cogvlm-chat --version chat --english --bf16
出现以下问题
RuntimeError: [1] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Connection reset by peer. This may indicate a possible application crash on rank 0 or a network set up issue.
[2023-11-17 07:24:11,710] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -9) local_rank: 0 (pid: 3382) of binary: /home/sfz/soft/miniconda3/envs/cogcu118/bin/python
torch.distributed.elastic.multiprocessing.errors.ChildFailedError
是NCCL设置的问题，还是模型本身还不支持多卡并行

**Comment by 1049451037** [comment]
模型本身肯定是支持多卡的，应该是你的本地环境的问题。

**Comment by elesun2018** [comment]
相同的环境，我试验了 分布式例子pytorch examples
https://github.com/pytorch/examples  \distributed\ddp-tutorial-series\multigpu_torchrun.py
ddp-tutorial-series# torchrun --standalone --nnodes=1 --nproc-per-node=gpu multigpu_torchrun.py 1000 10
正常，可以启动单机多卡 2*3090
但是运行torchrun --standalone --nnodes=1 --nproc-per-node=2 cli_demo.py --from_pretrained cogvlm-chat --version chat --english --bf16
还是出现上述问题RuntimeError: [1] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0'
估计是什么原因，谢谢

**Comment by 1049451037** [comment]
https://blog.csdn.net/qq874455953/article/details/134408257

看起来像是网络名字配置错误

**Comment by elesun2018** [comment]
这个之前试验过，export NCCL_SOCKET_IFNAME=enp7s0，还是同样的问题。
如果是NCCL配置的问题，multigpu_torchrun.py应该也会跑不通吧
现在是pytorch multigpu_torchrun.py可以启动单机多卡，cli_demo.py不可以，估计是什么原因

**Comment by 1049451037** [comment]
如果运行不起来，可以尝试跑huggingface版本：https://huggingface.co/THUDM/cogvlm-chat-hf
