### ISSUE TITLE
Merge the finetune model 

### ISSUE THREAD

**Issue by wlw208dzy** [THUDM/CogVLM#117]
谢谢作者，我们训练得到的checkpoint模型存在了finetune-XXXX文件夹中，现在想调用merge代码整合后进行测试，但是在merge过程中报了如下错误，直接merge最终的模型结果（merge_lora文件夹）没有问题：
[2023-11-22 03:26:54,041] [INFO] [RANK 0]  > number of parameters on model parallel rank 0: 17657466368

[2023-11-22 03:27:10,971] [INFO] [RANK 0] > initializing model parallel with size 4

Traceback (most recent call last):

  File "/home/deep/env/CogVLM-new/merge_model.py", line 42, in <module>

    main()

  File "/home/deep/env/CogVLM-new/merge_model.py", line 23, in main

    model, model_args = FineTuneTestCogVLMModel.from_pretrained(

  File "/home/deep/anaconda3/lib/python3.9/site-packages/sat/model/base_model.py", line 257, in from_pretrained

    mp_merge_model_rank0(model, model_full)

  File "/home/deep/anaconda3/lib/python3.9/site-packages/sat/mpu/operation.py", line 108, in mp_merge_model_rank0

    iter_merge(model, model_full)

  File "/home/deep/anaconda3/lib/python3.9/site-packages/sat/mpu/operation.py", line 107, in iter_merge

    iter_merge(sub_new_model, sub_module)

  File "/home/deep/anaconda3/lib/python3.9/site-packages/sat/mpu/operation.py", line 107, in iter_merge

    iter_merge(sub_new_model, sub_module)

  File "/home/deep/anaconda3/lib/python3.9/site-packages/sat/mpu/operation.py", line 107, in iter_merge

    iter_merge(sub_new_model, sub_module)

  [Previous line repeated 5 more times]

  File "/home/deep/anaconda3/lib/python3.9/site-packages/sat/mpu/operation.py", line 106, in iter_merge

    p.data.copy_(torch.clone(np.data).detach())

RuntimeError: The size of tensor a (1792) must match the size of tensor b (448) at non-singleton dimension 0

Traceback (most recent call last):

  File "/home/deep/env/CogVLM-new/merge_model.py", line 42, in <module>

    main()

  File "/home/deep/env/CogVLM-new/merge_model.py", line 23, in main

    model, model_args = FineTuneTestCogVLMModel.from_pretrained(

  File "/home/deep/anaconda3/lib/python3.9/site-packages/sat/model/base_model.py", line 263, in from_pretrained

    initialize_model_parallel(1)

  File "/home/deep/anaconda3/lib/python3.9/site-packages/sat/mpu/initialize.py", line 69, in initialize_model_parallel

    group = torch.distributed.new_group(ranks)

  File "/home/deep/anaconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 3544, in new_group

    _store_based_barrier(global_rank, default_store, timeout)

  File "/home/deep/anaconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 441, in _store_based_barrier

    store.add(store_key, 1)

RuntimeError: Broken pipe

Traceback (most recent call last):

  File "/home/deep/env/CogVLM-new/merge_model.py", line 42, in <module>

    main()

  File "/home/deep/env/CogVLM-new/merge_model.py", line 23, in main

    model, model_args = FineTuneTestCogVLMModel.from_pretrained(

  File "/home/deep/anaconda3/lib/python3.9/site-packages/sat/model/base_model.py", line 263, in from_pretrained

    initialize_model_parallel(1)

  File "/home/deep/anaconda3/lib/python3.9/site-packages/sat/mpu/initialize.py", line 69, in initialize_model_parallel

    group = torch.distributed.new_group(ranks)

  File "/home/deep/anaconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 3544, in new_group

    _store_based_barrier(global_rank, default_store, timeout)

  File "/home/deep/anaconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 441, in _store_based_barrier

    store.add(store_key, 1)

RuntimeError: Broken pipe

Traceback (most recent call last):

  File "/home/deep/env/CogVLM-new/merge_model.py", line 42, in <module>

    main()

  File "/home/deep/env/CogVLM-new/merge_model.py", line 23, in main

    model, model_args = FineTuneTestCogVLMModel.from_pretrained(

  File "/home/deep/anaconda3/lib/python3.9/site-packages/sat/model/base_model.py", line 263, in from_pretrained

    initialize_model_parallel(1)

  File "/home/deep/anaconda3/lib/python3.9/site-packages/sat/mpu/initialize.py", line 69, in initialize_model_parallel

    group = torch.distributed.new_group(ranks)

  File "/home/deep/anaconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 3544, in new_group

    _store_based_barrier(global_rank, default_store, timeout)

  File "/home/deep/anaconda3/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 441, in _store_based_barrier

    store.add(store_key, 1)

RuntimeError: Broken pipe

WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 21627 closing signal SIGTERM

WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 21628 closing signal SIGTERM

WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 21629 closing signal SIGTERM

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 21626) of binary: /home/deep/anaconda3/bin/python

Traceback (most recent call last):

  File "/home/deep/anaconda3/bin/torchrun", line 8, in <module>

    sys.exit(main())

  File "/home/deep/anaconda3/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper

    return f(*args, **kwargs)

  File "/home/deep/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main

    run(args)

  File "/home/deep/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run

    elastic_launch(

  File "/home/deep/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__

    return launch_agent(self._config, self._entrypoint, list(args))

  File "/home/deep/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent

    raise ChildFailedError(

torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

============================================================

merge_model.py FAILED

------------------------------------------------------------

Failures:

  <NO_OTHER_FAILURES>

------------------------------------------------------------

Root Cause (first observed failure):

[0]:

  time      : 2023-11-22_03:27:15

  host      : 6e723bb9be15

  rank      : 0 (local_rank: 0)

  exitcode  : 1 (pid: 21626)

  error_file: <N/A>

  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by 1049451037** [comment]
测试可以直接用evaluate_demo.py。merge只是为了让模型用cli_demo.py加载推理。

**Comment by GondorFu** [comment]
> 测试可以直接用evaluate_demo.py，merge只是为了让模型用cli_demo.py加载推理。如果想用finetune保存的checkpoint进行merge操作，可以在evaluate_demo.py里加入这段merge代码：
> 
> https://github.com/THUDM/CogVLM/blob/2d85b29ddcf4028e138641d9e72920762177627d/finetune_demo.py#L256-L262

这个直接添加会报 model_parallel_size 不一致的错误呀
