### ISSUE TITLE
请问8卡3090 多卡微调CogVLM 224，这是报什么错么,

### ISSUE THREAD

**Issue by libaihome** [THUDM/CogVLM#121]
请问8卡3090 多卡微调CogVLM 224，这是报什么错么,
<img width="853" alt="微信图片_20231122185538" src="https://github.com/THUDM/CogVLM/assets/128136782/c803f48d-2246-4fd0-b508-4a9e45d83611">

另外2卡3090推理，会卡在这个界面，是哪里的配置问题吗
![微信截图_20231122185706](https://github.com/THUDM/CogVLM/assets/128136782/bbcda56c-9fb1-4c91-ba73-2ab075c9dc5f)

<img width="1688" alt="微信图片_20231122185815" src="https://github.com/THUDM/CogVLM/assets/128136782/5bf05a06-314c-4921-b08b-eba55894e8f8">

**Comment by 1049451037** [comment]
模型的checkpoint已经变了，请更新到最新的github代码，并且使用cogvlm-chat-v1.1作为模型名称

**Comment by libaihome** [comment]
[2023-11-25 01:33:49,065] [INFO] [checkpointing.py:545:forward] ----Profiling time in checkpointing False
Traceback (most recent call last):
  File "/mnt/f/ai/CogVLM/finetune_demo.py", line 255, in <module>
Traceback (most recent call last):
  File "/mnt/f/ai/CogVLM/finetune_demo.py", line 255, in <module>
    model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor), collate_fn=data_collator, forward_step_eval=forward_step_eval)    
model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor), collate_fn=data_collator, forward_step_eval=forward_step_eval)
             ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^  File "/home/baiyu/anaconda3/envs/yolo/lib/python3.11/site-packages/sat/training/deepspeed_training.py", line 130, in training_main
^^^^^^
  File "/home/baiyu/anaconda3/envs/yolo/lib/python3.11/site-packages/sat/training/deepspeed_training.py", line 130, in training_main
    iteration, skipped = train(model, optimizer,
       iteration, skipped = train(model, optimizer, 
                                      ^ ^ ^ ^ ^ ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^  File "/home/baiyu/anaconda3/envs/yolo/lib/python3.11/site-packages/sat/training/deepspeed_training.py", line 299, in train
^^^^^
  File "/home/baiyu/anaconda3/envs/yolo/lib/python3.11/site-packages/sat/training/deepspeed_training.py", line 299, in train
    lm_loss, skipped_iter, metrics = train_step(train_data_iterator,
         lm_loss, skipped_iter, metrics = train_step(train_data_iterator, 
                                                           ^ ^ ^ ^ ^ ^ ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^  File "/home/baiyu/anaconda3/envs/yolo/lib/python3.11/site-packages/sat/training/deepspeed_training.py", line 373, in train_step
^^^^^
  File "/home/baiyu/anaconda3/envs/yolo/lib/python3.11/site-packages/sat/training/deepspeed_training.py", line 373, in train_step
    forward_ret = forward_step(data_iterator, model, args, timers, **kwargs)
    forward_ret = forward_step(data_iterator, model, args, timers, **kwargs)
                      ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^  File "/mnt/f/ai/CogVLM/finetune_demo.py", line 211, in forward_step
^^^^^^^^^^^
  File "/mnt/f/ai/CogVLM/finetune_demo.py", line 211, in forward_step
    loss = loss_fct(shift_logits.view(-1, shift_logits.size(-1)), shift_labels.view(-1))
    loss = loss_fct(shift_logits.view(-1, shift_logits.size(-1)), shift_labels.view(-1))
                  ^ ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^  File "/home/baiyu/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl

  File "/home/baiyu/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)    
return self._call_impl(*args, **kwargs)
                    ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^
  File "/home/baiyu/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
  File "/home/baiyu/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
    return forward_call(*args, **kwargs)
              ^ ^ ^ ^ ^ ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^  File "/home/baiyu/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/nn/modules/loss.py", line 1179, in forward
^^^^^
  File "/home/baiyu/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/nn/modules/loss.py", line 1179, in forward
        return F.cross_entropy(input, target, weight=self.weight,return F.cross_entropy(input, target, weight=self.weight,

                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/baiyu/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/nn/functional.py", line 3053, in cross_entropy
  File "/home/baiyu/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/nn/functional.py", line 3053, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)    
return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
             ^ ^ ^ ^ ^ ^ ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.21 GiB. GPU 5 has a total capacty of 23.69 GiB of which 1.19 GiB is free. Including non-PyTorch memory, this process has 22.48 GiB memory in use. Of the allocated memory 17.77 GiB is allocated by PyTorch, and 4.25 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.21 GiB. GPU 7 has a total capacty of 23.69 GiB of which 1.19 GiB is free. Including non-PyTorch memory, this process has 22.48 GiB memory in use. Of the allocated memory 17.77 GiB is allocated by PyTorch, and 4.25 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "/mnt/f/ai/CogVLM/finetune_demo.py", line 255, in <module>
    model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor), collate_fn=data_collator, forward_step_eval=forward_step_eval)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/baiyu/anaconda3/envs/yolo/lib/python3.11/site-packages/sat/training/deepspeed_training.py", line 130, in training_main
    iteration, skipped = train(model, optimizer,
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/baiyu/anaconda3/envs/yolo/lib/python3.11/site-packages/sat/training/deepspeed_training.py", line 299, in train
    lm_loss, skipped_iter, metrics = train_step(train_data_iterator,
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/baiyu/anaconda3/envs/yolo/lib/python3.11/site-packages/sat/training/deepspeed_training.py", line 373, in train_step
    forward_ret = forward_step(data_iterator, model, args, timers, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/f/ai/CogVLM/finetune_demo.py", line 211, in forward_step
    loss = loss_fct(shift_logits.view(-1, shift_logits.size(-1)), shift_labels.view(-1))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/baiyu/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/baiyu/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/baiyu/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/nn/modules/loss.py", line 1179, in forward
    return F.cross_entropy(input, target, weight=self.weight,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/baiyu/anaconda3/envs/yolo/lib/python3.11/site-packages/torch/nn/functional.py", line 3053, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.21 GiB. GPU 1 has a total capacty of 23.69 GiB of which 1.13 GiB is free. Including non-PyTorch memory, this process has 22.54 GiB memory in use. Of the allocated memory 17.77 GiB is allocated by PyTorch, and 4.31 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[2023-11-25 01:35:13,838] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 12838
[2023-11-25 01:35:15,020] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 12839
[2023-11-25 01:35:15,046] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 12840
[2023-11-25 01:35:15,764] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 12841
[2023-11-25 01:35:16,552] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 12842
[2023-11-25 01:35:17,539] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 12843
[2023-11-25 01:35:17,564] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 12844
[2023-11-25 01:35:18,509] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 12845
[2023-11-25 01:35:18,509] [ERROR] [launch.py:321:sigkill_handler] ['/home/baiyu/anaconda3/envs/yolo/bin/python', '-u', 'finetune_demo.py', '--local_rank=7', '--experiment-name', 'finetune-cogvlm-base-224', '--model-parallel-size', '4', '--mode', 'finetune', '--train-iters', '800', '--resume-dataloader', '--from_pretrained', 'cogvlm-base-224', '--max_length', '319', '--lora_rank', '10', '--use_lora', '--local_tokenizer', 'lmsys/vicuna-7b-v1.5', '--version', 'base', '--train-data', './archive_split/train', '--valid-data', './archive_split/valid', '--distributed-backend', 'nccl', '--lr-decay-style', 'cosine', '--warmup', '.02', '--checkpoint-activations', '--vit_checkpoint_activations', '--save-interval', '200', '--eval-interval', '200', '--save', './checkpoints', '--eval-iters', '10', '--eval-batch-size', '1', '--split', '1.', '--deepspeed_config', 'scripts/test_config_bf16.json', '--skip-init', '--seed', '2023'] exits with return code = 1
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
我运行的是这个，bash scripts/finetune_224_lora.sh，提感觉像显存不足，大神您确定8*3090能跑么，^_^

**Comment by pf67** [comment]
> CUDA out of memory. Tried to allocate 1.21 GiB.
4个3090应该能稳定跑了。
但是你如果是用224_lora.sh，你最好check一下对应的deepseed配置文件，我记得里面默认把batchsize设置为了32，反正我用490的sh，对应bathsize只能设置为8，再大就爆了，224的我没试，你可以改小一些试试

**Comment by libaihome** [comment]
感谢 国货之光 加油
