### ISSUE TITLE
WSL2下载模型出错，本地从抱脸拉的模型不认还要下。

### ISSUE THREAD

**Issue by Yoimiyacat** [THUDM/CogVLM#126]
系统：Ubuntu22.04_WSL
在/mnt/d/CogVLM下git clone了https://huggingface.co/THUDM/CogVLM/

(venv)yoimiya:~/cogvlm$ python web_demo.py --from_pretrained cogvlm-chat-v1.1 --version chat --english --bf16

报错：
[2023-11-24 10:51:26,440] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Downloading models r2://cogvlm-chat-v1.1.zip into /mnt/d/CogVLM ...
/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'c8a00746a80e06c4632028e37de24d6e.r2.cloudflarestorage.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Failed to download or check, if you already had the zip file, please unzip it manually as /mnt/d/CogVLM/cogvlm-chat-v1.1!
Traceback (most recent call last):
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/urllib3/response.py", line 710, in _error_catcher
    yield
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/urllib3/response.py", line 835, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(3538944 bytes read, 4849664 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/botocore/response.py", line 99, in read
    chunk = self._raw_stream.read(amt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/urllib3/response.py", line 879, in read
    data = self._raw_read(amt)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/urllib3/response.py", line 813, in _raw_read
    with self._error_catcher():
  File "/home/yoimiya/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/urllib3/response.py", line 727, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(3538944 bytes read, 4849664 more expected)', IncompleteRead(3538944 bytes read, 4849664 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yoimiya/cogvlm/web_demo.py", line 222, in <module>
    main(args)
  File "/home/yoimiya/cogvlm/web_demo.py", line 144, in main
    model, image_processor, text_processor_infer = load_model(args)
                                                   ^^^^^^^^^^^^^^^^
  File "/home/yoimiya/cogvlm/web_demo.py", line 53, in load_model
    model, model_args = CogVLMModel.from_pretrained(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/sat/model/base_model.py", line 215, in from_pretrained
    return cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=build_only, overwrite_args=overwrite_args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/sat/model/base_model.py", line 201, in from_pretrained_base
    model_path = auto_create(name, path=home_path, url=url)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/sat/resources/download.py", line 68, in auto_create
    raise e
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/sat/resources/download.py", line 62, in auto_create
    download_s3(path, url[5:])
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/sat/resources/download.py", line 108, in download_s3
    bucket.download_file(remote_uri, os.path.join(local_dir, os.path.basename(remote_uri)),Callback=ProgressPercentage(client, SAT_BUCKET, remote_uri), Config=transfer_config)
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/boto3/s3/inject.py", line 277, in bucket_download_file
    return self.meta.client.download_file(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/boto3/s3/inject.py", line 190, in download_file
    return transfer.download_file(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/boto3/s3/transfer.py", line 326, in download_file
    future.result()
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/s3transfer/tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/s3transfer/tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/s3transfer/download.py", line 583, in _main
    for chunk in chunks:
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/s3transfer/download.py", line 728, in __next__
    chunk = self._body.read(self._chunksize)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/s3transfer/utils.py", line 599, in read
    value = self._stream.read(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/botocore/response.py", line 104, in read
    raise ResponseStreamingError(error=e)
botocore.exceptions.ResponseStreamingError: An error occurred while reading from response stream: ('Connection broken: IncompleteRead(3538944 bytes read, 4849664 more expected)', IncompleteRead(3538944 bytes read, 4849664 more expected))

**Comment by 1049451037** [comment]
WSL2应该需要运行这个版本：https://huggingface.co/THUDM/cogvlm-chat-hf

https://github.com/THUDM/CogVLM

**Comment by Yoimiyacat** [comment]
我把它解压了，就能用本地模型了，但是又产生了报错：
(venv) yoimiya:~/cogvlm$ python web_demo.py --from_pretrained cogvlm-chat-v1.1 --version chat --english --bf16
[2023-11-24 11:23:42,133] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-11-24 11:23:43,339] [INFO] building CogVLMModel model ...
[2023-11-24 11:23:43,348] [INFO] [RANK 0] > initializing model parallel with size 1
[2023-11-24 11:23:43,349] [INFO] [RANK 0] You are using model-only mode.
For torch.distributed users or loading model parallel models, set environment variables RANK, WORLD_SIZE and LOCAL_RANK.
[2023-11-24 11:23:49,665] [INFO] [RANK 0]  > number of parameters on model parallel rank 0: 17639685376
[2023-11-24 11:24:04,983] [INFO] [RANK 0] global rank 0 is loading checkpoint /mnt/d/CogVLM/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt
Killed

**Comment by 1049451037** [comment]
确保你有一张80G的显卡才能这样运行。否则请使用多卡运行配置，在readme里有，用torchrun启动。

**Comment by Yoimiyacat** [comment]
> 确保你有一张80G的显卡才能这样运行。否则请使用多卡运行配置，在readme里有，用torchrun启动。
谢谢，确实需要torchrun，这样才能用共享显存，但是，又报错了：
(venv) yoimiya:~/cogvlm$ torchrun --standalone --nnodes=1 --nproc-per-node=1 web_demo.py -- --from_pretrained cogvlm-chat-v1.1 --version chat --english --bf16
[2023-11-24 15:14:35,903] torch.distributed.run: [WARNING] master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
[2023-11-24 15:14:38,442] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-11-24 15:14:39,493] [INFO] building CogVLMModel model ...
[2023-11-24 15:14:39,494] [INFO] [RANK 0] > initializing model parallel with size 1
[2023-11-24 15:14:39,495] [INFO] [RANK 0] You are using model-only mode.
For torch.distributed users or loading model parallel models, set environment variables RANK, WORLD_SIZE and LOCAL_RANK.
[2023-11-24 15:14:44,673] [INFO] [RANK 0]  > number of parameters on model parallel rank 0: 17639685376
[2023-11-24 15:14:52,051] [INFO] [RANK 0] global rank 0 is loading checkpoint /mnt/c/data/cogvlm/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt
[2023-11-24 15:15:38,574] [INFO] [RANK 0] > successfully loaded /mnt/c/data/cogvlm/cogvlm-chat-v1.1/1/mp_rank_00_model_states.pt
/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/gradio/layouts/column.py:55: UserWarning: 'scale' value should be an integer. Using 4.5 will cause issues.
  warnings.warn(
/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/gradio/layouts/column.py:55: UserWarning: 'scale' value should be an integer. Using 5.5 will cause issues.
  warnings.warn(
Traceback (most recent call last):
  File "/home/yoimiya/cogvlm/web_demo.py", line 222, in <module>
    main(args)
  File "/home/yoimiya/cogvlm/web_demo.py", line 178, in main
    result_text = gr.components.Chatbot(label='Multi-round conversation History', value=[("", "Hi, What do you want to know about this image?")]).style(height=550)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Chatbot' object has no attribute 'style'. Did you mean: 'scale'?
[2023-11-24 15:15:46,179] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 718) of binary: /home/yoimiya/cogvlm/venv/bin/python3
Traceback (most recent call last):
  File "/home/yoimiya/cogvlm/venv/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoimiya/cogvlm/venv/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
web_demo.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-24_15:15:46
  host      : yoimiya.
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 718)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by 1049451037** [comment]
`torchrun --standalone --nnodes=1 --nproc-per-node=1`这还是单卡呀……和直接python没区别。


关于`AttributeError: 'Chatbot' object has no attribute 'style'. Did you mean: 'scale'?`这个报错，是gradio版本的问题：https://github.com/THUDM/CogVLM/issues/82

**Comment by Yoimiyacat** [comment]
> `torchrun --standalone --nnodes=1 --nproc-per-node=1`这还是单卡呀……和直接python没区别。
> 
> 关于`AttributeError: 'Chatbot' object has no attribute 'style'. Did you mean: 'scale'?`这个报错，是gradio版本的问题：#82
虽然还是单卡，但是能调用共享显存，就能跑得动了（我内存大）
