### ISSUE TITLE
权重下载时报错Bad Request

### ISSUE THREAD

**Issue by xxheyu** [THUDM/CogVLM#140]
您好，在复现demo时遇到了一些问题，辛苦帮忙看一下～
运行命令
```shell
python cli_demo.py --from_pretrained cogvlm-chat-v1.1 --version chat --english --bf16
``` 
报错如下
```shell
/home/heyu/anaconda3/envs/cogvlm/lib/python3.9/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'c8a00746a80e06c4632028e37de24d6e.r2.cloudflarestorage.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
Failed to download or check, if you already had the zip file, please unzip it manually as /home/heyu/.sat_models/cogvlm-chat-v1.1!
Traceback (most recent call last):
  File "/mnt/disk1/yuhe/codes/CogVLM/cli_demo.py", line 154, in <module>
    main()
  File "/mnt/disk1/yuhe/codes/CogVLM/cli_demo.py", line 34, in main
    model, model_args = CogVLMModel.from_pretrained(
  File "/home/heyu/anaconda3/envs/cogvlm/lib/python3.9/site-packages/sat/model/base_model.py", line 215, in from_pretrained
    return cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=build_only, overwrite_args=overwrite_args, **kwargs)
  File "/home/heyu/anaconda3/envs/cogvlm/lib/python3.9/site-packages/sat/model/base_model.py", line 201, in from_pretrained_base
    model_path = auto_create(name, path=home_path, url=url)
  File "/home/heyu/anaconda3/envs/cogvlm/lib/python3.9/site-packages/sat/resources/download.py", line 68, in auto_create
    raise e
  File "/home/heyu/anaconda3/envs/cogvlm/lib/python3.9/site-packages/sat/resources/download.py", line 62, in auto_create
    download_s3(path, url[5:])
  File "/home/heyu/anaconda3/envs/cogvlm/lib/python3.9/site-packages/sat/resources/download.py", line 108, in download_s3
    bucket.download_file(remote_uri, os.path.join(local_dir, os.path.basename(remote_uri)),Callback=ProgressPercentage(client, SAT_BUCKET, remote_uri), Config=transfer_config)
  File "/home/heyu/anaconda3/envs/cogvlm/lib/python3.9/site-packages/sat/resources/download.py", line 134, in __init__
    self._size = client.head_object(Bucket=bucket, Key=filename)['ContentLength']
  File "/home/heyu/anaconda3/envs/cogvlm/lib/python3.9/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/heyu/anaconda3/envs/cogvlm/lib/python3.9/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (400) when calling the HeadObject operation: Bad Request
``` 
没有权限访问c8a00746a80e06c4632028e37de24d6e.r2.cloudflarestorage.com

**Comment by mactavish91** [comment]
可以手动在魔搭或者huggingface下载checkpoint，然后把from_pretrained的参数替换成checkpoint的本地路径
