### ISSUE TITLE
bitsandbytes Error running the huggingface example

### ISSUE THREAD

**Issue by JonathanRayner** [THUDM/CogVLM#148]
I get this error:

```
Detected the presence of a `quantization_config` attribute in the model's configuration but you don't have the correct `bitsandbytes` version to support int8 serialization. Please install the latest version of `bitsandbytes` with  `pip install --upgrade bitsandbytes`.
Loading checkpoint shards:   0%|          | 0/4 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 342, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 460, in run_inputs
    res = imp_fun.fun(*args, **kwargs)
  File "/root/model.py", line 191, in save_pretrained_to_volume
    AutoModelForCausalLM.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3480, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3870, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 751, in _load_state_dict_into_meta_model
    set_module_quantized_tensor_to_device(
  File "/opt/conda/lib/python3.10/site-packages/transformers/integrations/bitsandbytes.py", line 58, in set_module_quantized_tensor_to_device
    if old_value.device == torch.device("meta") and device not in ["meta", torch.device("meta")] and value is None:
NameError: name 'torch' is not defined
```

My `requirements.txt` following the [huggingface README](https://huggingface.co/THUDM/cogvlm-chat-hf):

```
torch==2.1.0
transformers==4.35.0
accelerate==0.24.1
sentencepiece==0.1.99
einops==0.7.0
xformers==0.0.22.post7
triton==2.1.0
```

and I'm using this [pytorch 2.1.0 docker container](https://hub.docker.com/layers/pytorch/pytorch/2.1.0-cuda12.1-cudnn8-devel/images/sha256-fe174e1e257d29976c99ebe9832d9bb20bd9706ea8eff1482cc9af261998c48d?context=explore) on an A100.

This error seems to be related to `bitsandbytes` not being part of the `requirements.txt`, but why do we need it when it wasn't needed/supported before? Also, if needed, will need to update the huggingface README.

**Comment by Sleepychord** [comment]
this is strange because it is a very basic python level error msg. Seems like you are using a buggy version of bitsandbytes. How about switch to a stable version?

**Comment by 1049451037** [comment]
We now support 4-bit quantization now! See README for more details.

**Comment by JonathanRayner** [comment]
> this is strange because it is a very basic python level error msg. Seems like you are using a buggy version of bitsandbytes. How about switch to a stable version?

I think it's just not installing `bitsandbytes` at all, when I add latest version to requirements it works. I can close the issue?
