### ISSUE TITLE
Finetune 时遇到报错，未找到文件

### ISSUE THREAD

**Issue by SoYuCry** [THUDM/CogVLM#184]
我遇到了报错：
[2023-12-12 20:04:04,813] [WARNING] Failed to load bitsandbytes:No module named 'scipy'
[2023-12-12 20:04:04,813] [WARNING] Failed to load bitsandbytes:No module named 'scipy'
[2023-12-12 20:04:04,813] [WARNING] Failed to load bitsandbytes:No module named 'scipy'
[2023-12-12 20:04:04,813] [WARNING] Failed to load bitsandbytes:No module named 'scipy'
[2023-12-12 20:04:04,813] [WARNING] Failed to load bitsandbytes:No module named 'scipy'
[2023-12-12 20:04:04,813] [WARNING] Failed to load bitsandbytes:No module named 'scipy'
[2023-12-12 20:04:04,814] [WARNING] Failed to load bitsandbytes:No module named 'scipy'
[2023-12-12 20:04:04,815] [WARNING] Failed to load bitsandbytes:No module named 'scipy'
[2023-12-12 20:04:05,539] [INFO] using world size: 8 and model-parallel size: 1 
[2023-12-12 20:04:05,539] [INFO] > padded vocab (size: 100) with 28 dummy tokens (new size: 128)
[2023-12-12 20:04:05,549] [INFO] Will override arguments with manually specified deepspeed_config!
Traceback (most recent call last):
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/Desktop/LiuC/LLM/CogVLM-main/finetune_demo.py", line 239, in <module>
Traceback (most recent call last):
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/Desktop/LiuC/LLM/CogVLM-main/finetune_demo.py", line 239, in <module>
    model, args = FineTuneTrainCogVLMModel.from_pretrained(args.from_pretrained, args, overwrite_args={'model_parallel_size': args.model_parallel_size} if args.model_parallel_size != 1 else {})
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/.conda/envs/CogVLM/lib/python3.10/site-packages/sat/model/base_model.py", line 215, in from_pretrained
    model, args = FineTuneTrainCogVLMModel.from_pretrained(args.from_pretrained, args, overwrite_args={'model_parallel_size': args.model_parallel_size} if args.model_parallel_size != 1 else {})
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/.conda/envs/CogVLM/lib/python3.10/site-packages/sat/model/base_model.py", line 215, in from_pretrained
    return cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=build_only, overwrite_args=overwrite_args, **kwargs)
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/.conda/envs/CogVLM/lib/python3.10/site-packages/sat/model/base_model.py", line 205, in from_pretrained_base
    return cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=build_only, overwrite_args=overwrite_args, **kwargs)
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/.conda/envs/CogVLM/lib/python3.10/site-packages/sat/model/base_model.py", line 205, in from_pretrained_base
    args = update_args_with_file(args, path=os.path.join(model_path, 'model_config.json'))
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/.conda/envs/CogVLM/lib/python3.10/site-packages/sat/arguments.py", line 446, in update_args_with_file
    args = update_args_with_file(args, path=os.path.join(model_path, 'model_config.json'))
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/.conda/envs/CogVLM/lib/python3.10/site-packages/sat/arguments.py", line 446, in update_args_with_file
Traceback (most recent call last):
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/Desktop/LiuC/LLM/CogVLM-main/finetune_demo.py", line 239, in <module>
    model, args = FineTuneTrainCogVLMModel.from_pretrained(args.from_pretrained, args, overwrite_args={'model_parallel_size': args.model_parallel_size} if args.model_parallel_size != 1 else {})
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/.conda/envs/CogVLM/lib/python3.10/site-packages/sat/model/base_model.py", line 215, in from_pretrained
    return cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=build_only, overwrite_args=overwrite_args, **kwargs)
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/.conda/envs/CogVLM/lib/python3.10/site-packages/sat/model/base_model.py", line 205, in from_pretrained_base
Traceback (most recent call last):
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/Desktop/LiuC/LLM/CogVLM-main/finetune_demo.py", line 239, in <module>
    args = update_args_with_file(args, path=os.path.join(model_path, 'model_config.json'))
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/.conda/envs/CogVLM/lib/python3.10/site-packages/sat/arguments.py", line 446, in update_args_with_file
    model, args = FineTuneTrainCogVLMModel.from_pretrained(args.from_pretrained, args, overwrite_args={'model_parallel_size': args.model_parallel_size} if args.model_parallel_size != 1 else {})
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/.conda/envs/CogVLM/lib/python3.10/site-packages/sat/model/base_model.py", line 215, in from_pretrained
    return cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=build_only, overwrite_args=overwrite_args, **kwargs)
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/.conda/envs/CogVLM/lib/python3.10/site-packages/sat/model/base_model.py", line 205, in from_pretrained_base
    args = update_args_with_file(args, path=os.path.join(model_path, 'model_config.json'))
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/.conda/envs/CogVLM/lib/python3.10/site-packages/sat/arguments.py", line 446, in update_args_with_file
Traceback (most recent call last):
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/Desktop/LiuC/LLM/CogVLM-main/finetune_demo.py", line 239, in <module>
    model, args = FineTuneTrainCogVLMModel.from_pretrained(args.from_pretrained, args, overwrite_args={'model_parallel_size': args.model_parallel_size} if args.model_parallel_size != 1 else {})
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/.conda/envs/CogVLM/lib/python3.10/site-packages/sat/model/base_model.py", line 215, in from_pretrained
    return cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=build_only, overwrite_args=overwrite_args, **kwargs)
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/.conda/envs/CogVLM/lib/python3.10/site-packages/sat/model/base_model.py", line 205, in from_pretrained_base
    args = update_args_with_file(args, path=os.path.join(model_path, 'model_config.json'))
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/.conda/envs/CogVLM/lib/python3.10/site-packages/sat/arguments.py", line 446, in update_args_with_file
Traceback (most recent call last):
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/Desktop/LiuC/LLM/CogVLM-main/finetune_demo.py", line 239, in <module>
    with open(path, 'r', encoding='utf-8') as f:        
with open(path, 'r', encoding='utf-8') as f:with open(path, 'r', encoding='utf-8') as f:FileNotFoundError

: FileNotFoundErrorFileNotFoundError[Errno 2] No such file or directory: '/lustre/home/acct-phyyjl/phyyjl-xzhr/Desktop/CogVLM/model_config.json': : 
[Errno 2] No such file or directory: '/lustre/home/acct-phyyjl/phyyjl-xzhr/Desktop/CogVLM/model_config.json'[Errno 2] No such file or directory: '/lustre/home/acct-phyyjl/phyyjl-xzhr/Desktop/CogVLM/model_config.json'

    with open(path, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/home/acct-phyyjl/phyyjl-xzhr/Desktop/CogVLM/model_config.json'
    model, args = FineTuneTrainCogVLMModel.from_pretrained(args.from_pretrained, args, overwrite_args={'model_parallel_size': args.model_parallel_size} if args.model_parallel_size != 1 else {})
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/.conda/envs/CogVLM/lib/python3.10/site-packages/sat/model/base_model.py", line 215, in from_pretrained
    with open(path, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/home/acct-phyyjl/phyyjl-xzhr/Desktop/CogVLM/model_config.json'
    return cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=build_only, overwrite_args=overwrite_args, **kwargs)
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/.conda/envs/CogVLM/lib/python3.10/site-packages/sat/model/base_model.py", line 205, in from_pretrained_base
    args = update_args_with_file(args, path=os.path.join(model_path, 'model_config.json'))
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/.conda/envs/CogVLM/lib/python3.10/site-packages/sat/arguments.py", line 446, in update_args_with_file
    with open(path, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/home/acct-phyyjl/phyyjl-xzhr/Desktop/CogVLM/model_config.json'
Traceback (most recent call last):
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/Desktop/LiuC/LLM/CogVLM-main/finetune_demo.py", line 239, in <module>
    model, args = FineTuneTrainCogVLMModel.from_pretrained(args.from_pretrained, args, overwrite_args={'model_parallel_size': args.model_parallel_size} if args.model_parallel_size != 1 else {})
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/.conda/envs/CogVLM/lib/python3.10/site-packages/sat/model/base_model.py", line 215, in from_pretrained
    return cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=build_only, overwrite_args=overwrite_args, **kwargs)
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/.conda/envs/CogVLM/lib/python3.10/site-packages/sat/model/base_model.py", line 205, in from_pretrained_base
    args = update_args_with_file(args, path=os.path.join(model_path, 'model_config.json'))
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/.conda/envs/CogVLM/lib/python3.10/site-packages/sat/arguments.py", line 446, in update_args_with_file
[2023-12-12 20:04:09,170] [INFO] [RANK 0] > initializing model parallel with size 1
    with open(path, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/home/acct-phyyjl/phyyjl-xzhr/Desktop/CogVLM/model_config.json'
Traceback (most recent call last):
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/Desktop/LiuC/LLM/CogVLM-main/finetune_demo.py", line 239, in <module>
    model, args = FineTuneTrainCogVLMModel.from_pretrained(args.from_pretrained, args, overwrite_args={'model_parallel_size': args.model_parallel_size} if args.model_parallel_size != 1 else {})
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/.conda/envs/CogVLM/lib/python3.10/site-packages/sat/model/base_model.py", line 215, in from_pretrained
    return cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=build_only, overwrite_args=overwrite_args, **kwargs)
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/.conda/envs/CogVLM/lib/python3.10/site-packages/sat/model/base_model.py", line 205, in from_pretrained_base
    args = update_args_with_file(args, path=os.path.join(model_path, 'model_config.json'))
  File "/lustre/home/acct-phyyjl/phyyjl-xzhr/.conda/envs/CogVLM/lib/python3.10/site-packages/sat/arguments.py", line 446, in update_args_with_file
    with open(path, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/home/acct-phyyjl/phyyjl-xzhr/Desktop/CogVLM/model_config.json'

这是我的文件列表，从这里下载的https://huggingface.co/THUDM/cogvlm-base-490-hf/tree/main，没有看到有model_config.json呢
![image](https://github.com/THUDM/CogVLM/assets/87529679/4f9c0464-35dd-4457-93f3-5ba6dffa1a19)

**Comment by z3ugma** [comment]
You have no file called `model_config.json' in that directory 

You have similarly named files, like `config.json` 
A package called `sat` has a file called `arguments.py`  with a function `update_args_with_file` and that file expects `model_config.json'

**Comment by z3ugma** [comment]
`pip install SwissArmyTransformer` is the sat package 

Maybe raise an issue here? https://github.com/THUDM/SwissArmyTransformer

**Comment by 1049451037** [comment]
hf version is not supported for fine-tuning. If you want to fine-tune, we suggest using sat version models.
