### ISSUE TITLE
Getting error `panic: runtime error: invalid memory address or nil pointer dereference` while infrenceing with CogAgent-chat-hf

### ISSUE THREAD

**Issue by OnlinePage** [THUDM/CogVLM#211]
hi🙂! I was trying to use the the recent announced model **cogagent-chat-hf** based on the [inference code given on 🤗](https://huggingface.co/THUDM/cogagent-chat-hf#quick-start)

However when i ran it , it resulted in below error trace ☹️

```python
Running prediction...
Traceback (most recent call last):
File "/root/.pyenv/versions/3.11.7/lib/python3.11/site-packages/cog/server/worker.py", line 217, in _predict
result = predict(**payload)
^^^^^^^^^^^^^^^^^^
File "/src/predict.py", line 76, in predict
outputs = self.model.generate(**inputs, **gen_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/root/.pyenv/versions/3.11.7/lib/python3.11/site-packages/transformers/generation/utils.py", line 1719, in generate
return self.sample(
^^^^^^^^^^^^
File "/root/.pyenv/versions/3.11.7/lib/python3.11/site-packages/transformers/generation/utils.py", line 2801, in sample
outputs = self(
^^^^^
File "/root/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/.cache/huggingface/modules/transformers_modules/THUDM/cogagent-chat-hf/b714305a4ab29b3b1d745fbd684c7d86e2ead286/modeling_cogagent.py", line 786, in forward
outputs = self.model(
^^^^^^^^^^^
File "/root/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/.cache/huggingface/modules/transformers_modules/THUDM/cogagent-chat-hf/b714305a4ab29b3b1d745fbd684c7d86e2ead286/modeling_cogagent.py", line 524, in forward
encoder_outputs = self.encode_cross_images(cross_images)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/.cache/huggingface/modules/transformers_modules/THUDM/cogagent-chat-hf/b714305a4ab29b3b1d745fbd684c7d86e2ead286/modeling_cogagent.py", line 487, in encode_cross_images
for image_list in images_list:
TypeError: 'NoneType' object is not iterable
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8ad41b]

goroutine 1 [running]:
github.com/replicate/cog/pkg/cli.predictIndividualInputs({{{0x0, 0x0, 0x0}, {0xc000302040, 0x1, 0x1}, {0x98f4e2, 0x3}, {0xc000286780, 0xf}, ...}, ...}, ...)
        /home/runner/work/cog/cog/pkg/cli/predict.go:198 +0x41b
github.com/replicate/cog/pkg/cli.cmdPredict(0xc00022cf00?, {0xc0001ec640?, 0x4?, 0x4?})
        /home/runner/work/cog/cog/pkg/cli/predict.go:153 +0x9be
github.com/spf13/cobra.(*Command).execute(0xc00022cf00, {0xc0001ec600, 0x4, 0x4})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc00022c000)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0xd92780?)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x19
main.main()
        /home/runner/work/cog/cog/cmd/cog/cog.go:14 +0x6f
```

Any help is highly appreciated 🙂!
my device :  gpu_1x_a6000

@zRzRzRzRzRzRzR

**Comment by zRzRzRzRzRzRzR** [comment]
do you try select your images? It seem like you do not send any images.
