### ISSUE TITLE
加载ckpt继续训练报错 model_parallel_size is inconsistent with prior configuration

### ISSUE THREAD

**Issue by EsonJohn** [THUDM/CogVLM#233]
我基于base模型lora finetune了几个epoch并且保存了ckpt，请问怎么加载ckpt继续训练呢。
我训练的时候设置NUM_GPUS_PER_WORKER=4，MP_SIZE=4。

加载ckpt继续训练的时候，我尝试把finetune_490_lora.sh中的MODEL_TYPE换成了ckpt的路径，NUM_GPUS_PER_WORKER和MP_SIZE和之前一样，但是报了以下错误：
```
Traceback (most recent call last):
  File "/root/workspace/zhangyi/CogVLM-main/finetune_demo.py", line 246, in <module>
    model, args = FineTuneTrainCogVLMModel.from_pretrained(args.from_pretrained, args, overwrite_args={'model_parallel_size': args.model_parallel_size} if args.model_parallel_size != 1 else {})
  File "/root/miniconda3/envs/zhangyi_CogVLM/lib/python3.9/site-packages/sat/model/base_model.py", line 229, in from_pretrained
    model_full, args_ = cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=False, overwrite_args=overwrite_args, **kwargs)
  File "/root/miniconda3/envs/zhangyi_CogVLM/lib/python3.9/site-packages/sat/model/base_model.py", line 207, in from_pretrained_base
    model = get_model(args, cls, **kwargs)
  File "/root/miniconda3/envs/zhangyi_CogVLM/lib/python3.9/site-packages/sat/model/base_model.py", line 379, in get_model
    model = model_cls(args, params_dtype=params_dtype, **kwargs)
  File "/root/workspace/zhangyi/CogVLM-main/models/cogvlm_model.py", line 125, in __init__
    super().__init__(args, transformer=transformer, parallel_output=parallel_output, **kw_args)
  File "/root/workspace/zhangyi/CogVLM-main/models/cogvlm_model.py", line 102, in __init__
    super().__init__(args, transformer=transformer, parallel_output=parallel_output, **kwargs)
  File "/root/miniconda3/envs/zhangyi_CogVLM/lib/python3.9/site-packages/sat/model/official/llama_model.py", line 101, in __init__
    super().__init__(args, transformer=transformer, parallel_output=parallel_output, layernorm=layernorm, activation_func=activation_func, **kwargs)
  File "/root/miniconda3/envs/zhangyi_CogVLM/lib/python3.9/site-packages/sat/model/base_model.py", line 88, in __init__
    success = _simple_init(model_parallel_size=args.model_parallel_size)
  File "/root/miniconda3/envs/zhangyi_CogVLM/lib/python3.9/site-packages/sat/arguments.py", line 308, in _simple_init
    if initialize_distributed(args): # first time init model parallel, print warning
  File "/root/miniconda3/envs/zhangyi_CogVLM/lib/python3.9/site-packages/sat/arguments.py", line 486, in initialize_distributed
    raise ValueError('model_parallel_size is inconsistent with prior configuration.'
ValueError: model_parallel_size is inconsistent with prior configuration.We currently do not support changing model_parallel_size.
```

**Comment by EsonJohn** [comment]
@1049451037 帮忙解答一下呗

**Comment by 1049451037** [comment]
继续训练需要把这一行的overwrite_args去掉

https://github.com/THUDM/CogVLM/blob/a39ea6e7be7d78da75affa855ea31139b8680f62/finetune_demo/finetune_cogvlm_demo.py#L240

**Comment by 1049451037** [comment]
但是上面这段的前提是你没有用lora训练。如果用了lora，那就只能像现在代码写的，最后merge好，再加载。

**Comment by EsonJohn** [comment]
> 但是上面这段的前提是你没有用lora训练。如果用了lora，那就只能像现在代码写的，最后merge好，再加载。

感谢回答。我用了lora训练并保存了ckpt，如果需要加载它重新训练，请问需要怎么merge呢

**Comment by 1049451037** [comment]
参考这里：https://github.com/THUDM/CogVLM/issues/117

**Comment by 1049451037** [comment]
最上面说的那段解决方法对于lora应该也行，不过我没试过，应该是可以的，如果有问题欢迎反馈。

**Comment by EsonJohn** [comment]
> 最上面说的那段解决方法对于lora应该也行，不过我没试过，应该是可以的，如果有问题欢迎反馈。

好的，感谢解答。我试一下。
