### ISSUE TITLE
KeyError: 'cogvlm-grounding-generalist'

### ISSUE THREAD

**Issue by hanswang1** [THUDM/CogVLM#242]
### System Info / 系統信息

1*A100 (40G) GPU
python 3.9

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

admin:~$ python cli_demo_sat.py --from_pretrained cogvlm-grounding-generalist --version base --bf16  --stream_chat
/home/itadmin/anaconda3/envs/detgpt/lib/python3.9/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
[2023-12-25 04:40:52,264] [INFO] DeepSpeed/CUDA is not installed, fallback to Pytorch checkpointing.
[2023-12-25 04:40:53,444] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Please 'pip install apex'
/home/itadmin/anaconda3/envs/detgpt/lib/python3.9/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/itadmin/anaconda3/envs/detgpt/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
Traceback (most recent call last):
  File "/home/itadmin/hans/2d/CogVLM/basic_demo/cli_demo_sat.py", line 161, in <module>
    main()
  File "/home/itadmin/hans/2d/CogVLM/basic_demo/cli_demo_sat.py", line 36, in main
    model, model_args = AutoModel.from_pretrained(
  File "/home/itadmin/anaconda3/envs/detgpt/lib/python3.9/site-packages/sat/model/base_model.py", line 337, in from_pretrained
    return cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=build_only, overwrite_args=overwrite_args, **kwargs)
  File "/home/itadmin/anaconda3/envs/detgpt/lib/python3.9/site-packages/sat/model/base_model.py", line 312, in from_pretrained_base
    model_path = auto_create(name, path=home_path, url=url)
  File "/home/itadmin/anaconda3/envs/detgpt/lib/python3.9/site-packages/sat/resources/download.py", line 53, in auto_create
    url = MODEL_URLS[name]
KeyError: 'cogvlm-grounding-generalist'

### Expected behavior / 期待表现

No error and CLI can be executed pass.

**Comment by 1049451037** [comment]
Please use `cogvlm-grounding-generalist-v1.1`.
