### ISSUE TITLE
Mac Support mps enabled

### ISSUE THREAD

**Issue by ageorgios** [THUDM/CogVLM#248]
### System Info / 系統信息

M1 Max Apple Sillicon

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

```
    model, model_args = AutoModel.from_pretrained(
        args.from_pretrained,
        args=argparse.Namespace(
        deepspeed=None,
        local_rank=rank,
        rank=rank,
        world_size=world_size,
        model_parallel_size=world_size,
        mode='inference',
        skip_init=True,
        use_gpu_initialization=True if (torch.cuda.is_available() and args.quant is None) else False,
        device='mps' if args.quant else 'cuda',
        **vars(args)
    ), overwrite_args={'model_parallel_size': world_size} if world_size != 1 else {})
    model = model.eval()
    from sat.mpu import get_model_parallel_world_size
    assert world_size == get_model_parallel_world_size(), "world size must equal to model parallel size for cli_demo!"
```

I have put mps
and installed this torch version
pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu
(https://developer.apple.com/metal/pytorch/)

I get
```
(.venv) ageorgios@mac CogVLM % python basic_demo/cli_demo_sat.py --from_pretrained '/Users/ageorgios/Models/cogagent-chat-hf' --version chat --stream_chat
[2023-12-26 22:18:30,155] [INFO] DeepSpeed/CUDA is not installed, fallback to Pytorch checkpointing.
Traceback (most recent call last):
  File "/Users/ageorgios/Models/CogVLM/basic_demo/cli_demo_sat.py", line 7, in <module>
    from sat.model.mixins import CachedAutoregressiveMixin
  File "/Users/ageorgios/Models/CogVLM/.venv/lib/python3.11/site-packages/sat/__init__.py", line 3, in <module>
    from .model import AutoModel
  File "/Users/ageorgios/Models/CogVLM/.venv/lib/python3.11/site-packages/sat/model/__init__.py", line 4, in <module>
    from .official import *
  File "/Users/ageorgios/Models/CogVLM/.venv/lib/python3.11/site-packages/sat/model/official/__init__.py", line 7, in <module>
    from .mae_model import MAE
  File "/Users/ageorgios/Models/CogVLM/.venv/lib/python3.11/site-packages/sat/model/official/mae_model.py", line 10, in <module>
    from sat.model.position_embedding import get_2d_sincos_pos_embed
  File "/Users/ageorgios/Models/CogVLM/.venv/lib/python3.11/site-packages/sat/model/position_embedding/__init__.py", line 4, in <module>
    from .triton_rotary_embeddings import FastRotaryEmbedding
  File "/Users/ageorgios/Models/CogVLM/.venv/lib/python3.11/site-packages/sat/model/position_embedding/triton_rotary_embeddings.py", line 6, in <module>
    from .triton_rotary import apply_rotary
  File "/Users/ageorgios/Models/CogVLM/.venv/lib/python3.11/site-packages/sat/model/position_embedding/triton_rotary.py", line 6, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
```

### Expected behavior / 期待表现

to run on Apple Sillicon after 'mps' device configuration

**Comment by 1049451037** [comment]
You can use hf version if you don't want to use triton.

**Comment by ageorgios** [comment]
python basic_demo/cli_demo_sat.py --from_pretrained '/Users/ageorgios/Models/cogagent-chat-hf' --version chat --stream_chat

Thank you for the answer,

I think I already use the cogagnet-chat-hf which is the hf version.

**Comment by 1049451037** [comment]
Then you downloaded wrong checkpoint. You can check here https://huggingface.co/THUDM/cogagent-chat-hf/blob/main/modeling_cogagent.py

There is no triton in it.

**Comment by Allisterlim** [comment]
Hi @ageorgios did you successfully run cogvlm on MPS? Are you using the M3 Pro 18GB unified memory with this repo: https://huggingface.co/THUDM/cogagent-chat-hf/tree/main ?
