### ISSUE TITLE
Traceback (most recent call last):   File "/home/hesham/CogVLM/basic_demo/cli_demo_sat.py", line 7, in <module>     from sat.model.mixins import CachedAutoregressiveMixin ModuleNotFoundError: No module named 'sat

### ISSUE THREAD

**Issue by h9-tect** [THUDM/CogVLM#252]
I  got this issue while run the installation 

"
```shell
Defaulting to user installation because normal site-packages is not writeable
Collecting sat
  Using cached sat-0.6.1.1.tar.bz2 (429 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-qitopiu4/sat_decd3080a7574a4aa6152fd2f11a5126/setup.py", line 129
          mode = ((os.stat(dest_name)[ST_MODE]) | 0555) & 07777
                                                  ^
      SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
``` 

I think it cuz of the sat is python-sat

**Comment by mactavish91** [comment]
You need ```pip install SwissArmyTransformer```.

**Comment by h9-tect** [comment]
I tried it , but gave mew same error?
