### ISSUE TITLE
Unable to Save QLoRA Finetuned Models

### ISSUE THREAD

**Issue by theo-pencisalo** [THUDM/CogVLM#257]
### System Info / 系統信息

cuda version: 11.8
HuggingFace `transformers` library version: 4.35.2
SwissArmyTransformer version: 0.4.8
Python version: 3.10.13
Operating system: Ubuntu 22.04.3 LTS

### Who can help? / 谁可以帮助到您？

@1049451037

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

It appears that the official script `finetune_cogagent_demo.py` supports QLoRA finetune CogAgent through SwissArmyTransformer library:
```python
# Some lines are omitted here
elif args.use_qlora:
        model.add_mixin("lora", LoraMixin(args.num_layers, args.lora_rank, layer_range=args.layer_range, qlora=True), reinit=True)
```
When this is enabled, the vRAM usage decreased dramatically. However, I met multiple problem when trying to save trained checkpoints.

### Problem 1

SwissArmyTransformer library assume all dense layers have bias. Here is a snippet from `sat/model/finetune/lora2.py`:
```python
def merge_linear_lora(lin):
    if lin.original.weight.data.dtype is not torch.uint8:
        weight = lin.original.weight
        out_dim, in_dim = weight.shape
        new_lin = nn.Linear(in_dim, out_dim, dtype=weight.data.dtype, bias=lin.original.bias is not None)
    else:
        import bitsandbytes.functional as F
        
        # This line will cause error
        weight = F.dequantize_fp4(lin.original.weight.data, lin.original.weight.quant_state).to(lin.original.bias.data.dtype)
        
        out_dim, in_dim = weight.shape
        new_lin = HackLinearNF4(in_dim, out_dim, bias=lin.original.bias is not None)
        # The rest is omitted
```
The problem can be solved by rewrite that line to `weight = F.dequantize_fp4(lin.original.weight.data, lin.original.weight.quant_state)`.

### Problem 2:

It seems like that if you didn't enable training LoRA on the vision transformer part, this part of the finetune_demo.py script will throw an error:
```python
    if args.use_lora:
        model.get_mixin("lora").merge_lora()
        
        # This line will thow an error.
        model.get_mixin("eva").vit_model.get_mixin("lora").merge_lora()
        
        args.use_lora = False
        args.save = "merged_lora_cogagent"
        from sat.training.model_io import save_checkpoint
        save_checkpoint(1, model, None, None, args) 
```
My solution is to comment it out.

### Problem 3:

After applying all changes mentioned above, this error occurred when saving merged checkpoint:
```
Traceback (most recent call last):
  File "/home/user/CogVLM/finetune_demo/finetune_cogagent_demo.py", line 303, in <module>
    save_checkpoint(1, model, None, None, args)
  File "/home/user/miniconda3/envs/env1/lib/python3.10/site-packages/sat/training/model_io.py", line 117, in save_checkpoint
    save_ds_checkpoint(iteration, model, lr_scheduler, args)
  File "/home/user/miniconda3/envs/env1/lib/python3.10/site-packages/sat/training/model_io.py", line 159, in save_ds_checkpoint
    save_ds_checkpoint_no_optim(model, args.save, str(iteration), client_state=sd)
  File "/home/user/miniconda3/envs/env1/lib/python3.10/site-packages/sat/training/model_io.py", line 170, in save_ds_checkpoint_no_optim
    model._save_checkpoint(save_dir, tag, client_state=client_state)
  File "/home/user/miniconda3/envs/env1/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 3209, in _save_checkpoint
    frozen_param_shapes=self._get_zero_frozen_param_attributes(self._get_param_shape_func)
  File "/home/user/miniconda3/envs/env1/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 3266, in _get_zero_frozen_param_attributes
    raise ValueError(f"failed to find frozen {param} in named params")
ValueError: failed to find frozen Parameter containing:
(omitted due to being a big uint8 quantized tensor)
```

### Problem 4:

After applying those changes mentioned above, when loading the checkpoint dumped during QLoRA training, another exception occurred:

```
NFO:sat:[RANK 0] global rank 0 is loading checkpoint /home/user/checkpoint/10000/mp_rank_00_model_states.pt
Traceback (most recent call last):
  File "/home/user/CogVLM/finetune_demo/evaluate_cogagent_demo.py", line 240, in <module>
    model, args = FineTuneTestCogAgentModel.from_pretrained(args.from_pretrained, args, overwrite_args={'model_parallel_size': args.model_parallel_size} if args.model_parallel_size != 1 else {})
  File "/home/user/miniconda3/envs/env1/lib/python3.10/site-packages/sat/model/base_model.py", line 215, in from_pretrained
    return cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=build_only, overwrite_args=overwrite_args, **kwargs)
  File "/home/user/miniconda3/envs/env1/lib/python3.10/site-packages/sat/model/base_model.py", line 209, in from_pretrained_base
    load_checkpoint(model, args, load_path=model_path, prefix=prefix)
  File "/home/user/miniconda3/envs/env1/lib/python3.10/site-packages/sat/training/model_io.py", line 241, in load_checkpoint
    missing_keys, unexpected_keys = module.load_state_dict(sd['module'], strict=False)
  File "/home/user/miniconda3/envs/env1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2138, in load_state_dict
    load(self, state_dict)
  File "/home/user/miniconda3/envs/env1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2126, in load
    load(child, child_state_dict, child_prefix)
  File "/home/user/miniconda3/envs/env1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2126, in load
    load(child, child_state_dict, child_prefix)
  File "/home/user/miniconda3/envs/env1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2126, in load
    load(child, child_state_dict, child_prefix)
  [Previous line repeated 3 more times]
  File "/home/user/miniconda3/envs/env1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2120, in load
    module._load_from_state_dict(
  File "/home/user/miniconda3/envs/env1/lib/python3.10/site-packages/sat/model/finetune/lora2.py", line 30, in _load_from_state_dict
    self.weight.data.copy_(state_dict[prefix+'weight'])
RuntimeError: The size of tensor a (12288) must match the size of tensor b (25165824) at non-singleton dimension 0
```
(I found out that 25165824 = 12288 * 4096 / 2, this might be helpful when guessing what happened.)

====================

It might be possible to train the model without `deepspeed`, but the memory usage increase is very significant.
I really appreciate the high quality model you open-sourced to the community, and I hope that being able to train QLoRA will make it more approachable. Thank you for the hard work!

### Expected behavior / 期待表现

The QLoRA should be merged into the model and then save normally.

**Comment by zRzRzRzRzRzRzR** [comment]
maybe disscusion in #270
