### ISSUE TITLE
WSL运行遇到问题

### ISSUE THREAD

**Issue by afezeriaWrnbbmm** [THUDM/CogVLM#265]
### System Info / 系統信息

WSL2

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

我在WSL运行python cli_demo_sat.py --from_pretrained cogvlm-chat-hf --fp16 --quant 8 --stream_chat
提示我
[2024-01-02 17:46:56,230] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Please 'pip install apex'
Traceback (most recent call last):
  File "/home/afezeria/dev_cogagent/basic_demo/cli_demo_sat.py", line 161, in <module>
    main()
  File "/home/afezeria/dev_cogagent/basic_demo/cli_demo_sat.py", line 36, in main
    model, model_args = AutoModel.from_pretrained(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/afezeria/miniconda3/lib/python3.11/site-packages/sat/model/base_model.py", line 337, in from_pretrained
    return cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=build_only, overwrite_args=overwrite_args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/afezeria/miniconda3/lib/python3.11/site-packages/sat/model/base_model.py", line 318, in from_pretrained_base
    args = update_args_with_file(args, path=os.path.join(model_path, 'model_config.json'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/afezeria/miniconda3/lib/python3.11/site-packages/sat/arguments.py", line 448, in update_args_with_file
    with open(path, 'r', encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'cogvlm-chat-hf/model_config.json'
但是模型里并没有这个文件

### Expected behavior / 期待表现

希望正常运行

**Comment by 1049451037** [comment]
因为你运行错了代码，hf要用cli_demo_hf来运行。
