### ISSUE TITLE
微调CogAgent-chat模型，MP_SIZE设为8，采用lora微调报错

### ISSUE THREAD

**Issue by VittorioDong** [THUDM/CogVLM#268]
### System Info / 系統信息

Cuda：11.8
Transformers：4.33.1
Python：3.8
操作系统：CentOS
GPU：8张A100（40GB显存）

### Who can help? / 谁可以帮助到您？

@1049451037

### Information / 问题信息

- [x] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. 修改finetune_demo/finetune_cogagent_lora.sh中的NUM_GPUS_PER_WORKER 和MP_SIZE均为8
```bash
NUM_GPUS_PER_WORKER=8
MP_SIZE=8
```
2. 执行微调脚本
```bash
bash finetune_demo/finetune_cogagent_lora.sh
```
3. 通过查看日志，报错如下：
```python
[2024-01-02 11:16:16,518] [INFO] [RANK 0] replacing layer 0 attention with lora
INFO:sat:[RANK 0] replacing layer 0 attention with lora
Traceback (most recent call last):
  File "finetune_demo/finetune_cogagent_demo.py", line 266, in <module>
Traceback (most recent call last):
    model.add_mixin("lora", LoraMixin(args.num_layers, args.lora_rank, layer_range=args.layer_range), reinit=True)
  File "/opt/conda/lib/python3.8/site-packages/sat/model/base_model.py", line 122, in add_mixin
  File "finetune_demo/finetune_cogagent_demo.py", line 266, in <module>
    new_mixin.reinit(self)  # also pass current mixins
  File "/opt/conda/lib/python3.8/site-packages/sat/model/finetune/lora2.py", line 195, in reinit
    parent_model.transformer.layers[i].cross_attention.dense = replace_linear_with_lora(parent_model.transformer.layers[i].cross_attention.dense, 1, self.r, self.lora_alpha, self.lora_dropout, qlora=self.qlora)
  File "/opt/conda/lib/python3.8/site-packages/sat/model/finetune/lora2.py", line 140, in replace_linear_with_lora
    new_layer = LoraLinear(original_cls, partition, in_dim, out_dim, r, *args, **kw_args, original_obj=lin)
  File "/opt/conda/lib/python3.8/site-packages/sat/model/finetune/lora2.py", line 93, in __init__
    self.original.weight.data.copy_(original_obj.weight.data.detach().clone())
RuntimeError: The size of tensor a (16) must match the size of tensor b (128) at non-singleton dimension 1
    model.add_mixin("lora", LoraMixin(args.num_layers, args.lora_rank, layer_range=args.layer_range), reinit=True)
  File "/opt/conda/lib/python3.8/site-packages/sat/model/base_model.py", line 122, in add_mixin
    new_mixin.reinit(self)  # also pass current mixins
  File "/opt/conda/lib/python3.8/site-packages/sat/model/finetune/lora2.py", line 195, in reinit
    parent_model.transformer.layers[i].cross_attention.dense = replace_linear_with_lora(parent_model.transformer.layers[i].cross_attention.dense, 1, self.r, self.lora_alpha, self.lora_dropout, qlora=self.qlora)
  File "/opt/conda/lib/python3.8/site-packages/sat/model/finetune/lora2.py", line 140, in replace_linear_with_lora
    new_layer = LoraLinear(original_cls, partition, in_dim, out_dim, r, *args, **kw_args, original_obj=lin)
  File "/opt/conda/lib/python3.8/site-packages/sat/model/finetune/lora2.py", line 93, in __init__
    self.original.weight.data.copy_(original_obj.weight.data.detach().clone())
RuntimeError: The size of tensor a (16) must match the size of tensor b (128) at non-singleton dimension 1
Traceback (most recent call last):
  File "finetune_demo/finetune_cogagent_demo.py", line 266, in <module>
    model.add_mixin("lora", LoraMixin(args.num_layers, args.lora_rank, layer_range=args.layer_range), reinit=True)
  File "/opt/conda/lib/python3.8/site-packages/sat/model/base_model.py", line 122, in add_mixin
    new_mixin.reinit(self)  # also pass current mixins
  File "/opt/conda/lib/python3.8/site-packages/sat/model/finetune/lora2.py", line 195, in reinit
    parent_model.transformer.layers[i].cross_attention.dense = replace_linear_with_lora(parent_model.transformer.layers[i].cross_attention.dense, 1, self.r, self.lora_alpha, self.lora_dropout, qlora=self.qlora)
  File "/opt/conda/lib/python3.8/site-packages/sat/model/finetune/lora2.py", line 140, in replace_linear_with_lora
    new_layer = LoraLinear(original_cls, partition, in_dim, out_dim, r, *args, **kw_args, original_obj=lin)
  File "/opt/conda/lib/python3.8/site-packages/sat/model/finetune/lora2.py", line 93, in __init__
    self.original.weight.data.copy_(original_obj.weight.data.detach().clone())
RuntimeError: The size of tensor a (16) must match the size of tensor b (128) at non-singleton dimension 1
Traceback (most recent call last):
  File "finetune_demo/finetune_cogagent_demo.py", line 266, in <module>
    model.add_mixin("lora", LoraMixin(args.num_layers, args.lora_rank, layer_range=args.layer_range), reinit=True)
  File "/opt/conda/lib/python3.8/site-packages/sat/model/base_model.py", line 122, in add_mixin
    new_mixin.reinit(self)  # also pass current mixins
  File "/opt/conda/lib/python3.8/site-packages/sat/model/finetune/lora2.py", line 195, in reinit
    parent_model.transformer.layers[i].cross_attention.dense = replace_linear_with_lora(parent_model.transformer.layers[i].cross_attention.dense, 1, self.r, self.lora_alpha, self.lora_dropout, qlora=self.qlora)
  File "/opt/conda/lib/python3.8/site-packages/sat/model/finetune/lora2.py", line 140, in replace_linear_with_lora
    new_layer = LoraLinear(original_cls, partition, in_dim, out_dim, r, *args, **kw_args, original_obj=lin)
  File "/opt/conda/lib/python3.8/site-packages/sat/model/finetune/lora2.py", line 93, in __init__
    self.original.weight.data.copy_(original_obj.weight.data.detach().clone())
RuntimeError: The size of tensor a (16) must match the size of tensor b (128) at non-singleton dimension 1
Traceback (most recent call last):
  File "finetune_demo/finetune_cogagent_demo.py", line 266, in <module>
    model.add_mixin("lora", LoraMixin(args.num_layers, args.lora_rank, layer_range=args.layer_range), reinit=True)
  File "/opt/conda/lib/python3.8/site-packages/sat/model/base_model.py", line 122, in add_mixin
    new_mixin.reinit(self)  # also pass current mixins
  File "/opt/conda/lib/python3.8/site-packages/sat/model/finetune/lora2.py", line 195, in reinit
    parent_model.transformer.layers[i].cross_attention.dense = replace_linear_with_lora(parent_model.transformer.layers[i].cross_attention.dense, 1, self.r, self.lora_alpha, self.lora_dropout, qlora=self.qlora)
  File "/opt/conda/lib/python3.8/site-packages/sat/model/finetune/lora2.py", line 140, in replace_linear_with_lora
    new_layer = LoraLinear(original_cls, partition, in_dim, out_dim, r, *args, **kw_args, original_obj=lin)
  File "/opt/conda/lib/python3.8/site-packages/sat/model/finetune/lora2.py", line 93, in __init__
    self.original.weight.data.copy_(original_obj.weight.data.detach().clone())
RuntimeError: The size of tensor a (16) must match the size of tensor b (128) at non-singleton dimension 1
Traceback (most recent call last):
  File "finetune_demo/finetune_cogagent_demo.py", line 266, in <module>
    model.add_mixin("lora", LoraMixin(args.num_layers, args.lora_rank, layer_range=args.layer_range), reinit=True)
  File "/opt/conda/lib/python3.8/site-packages/sat/model/base_model.py", line 122, in add_mixin
    new_mixin.reinit(self)  # also pass current mixins
  File "/opt/conda/lib/python3.8/site-packages/sat/model/finetune/lora2.py", line 195, in reinit
    parent_model.transformer.layers[i].cross_attention.dense = replace_linear_with_lora(parent_model.transformer.layers[i].cross_attention.dense, 1, self.r, self.lora_alpha, self.lora_dropout, qlora=self.qlora)
  File "/opt/conda/lib/python3.8/site-packages/sat/model/finetune/lora2.py", line 140, in replace_linear_with_lora
    new_layer = LoraLinear(original_cls, partition, in_dim, out_dim, r, *args, **kw_args, original_obj=lin)
  File "/opt/conda/lib/python3.8/site-packages/sat/model/finetune/lora2.py", line 93, in __init__
    self.original.weight.data.copy_(original_obj.weight.data.detach().clone())
RuntimeError: The size of tensor a (16) must match the size of tensor b (128) at non-singleton dimension 1
Traceback (most recent call last):
  File "finetune_demo/finetune_cogagent_demo.py", line 266, in <module>
    model.add_mixin("lora", LoraMixin(args.num_layers, args.lora_rank, layer_range=args.layer_range), reinit=True)
  File "/opt/conda/lib/python3.8/site-packages/sat/model/base_model.py", line 122, in add_mixin
    new_mixin.reinit(self)  # also pass current mixins
  File "/opt/conda/lib/python3.8/site-packages/sat/model/finetune/lora2.py", line 195, in reinit
    parent_model.transformer.layers[i].cross_attention.dense = replace_linear_with_lora(parent_model.transformer.layers[i].cross_attention.dense, 1, self.r, self.lora_alpha, self.lora_dropout, qlora=self.qlora)
  File "/opt/conda/lib/python3.8/site-packages/sat/model/finetune/lora2.py", line 140, in replace_linear_with_lora
    new_layer = LoraLinear(original_cls, partition, in_dim, out_dim, r, *args, **kw_args, original_obj=lin)
  File "/opt/conda/lib/python3.8/site-packages/sat/model/finetune/lora2.py", line 93, in __init__
    self.original.weight.data.copy_(original_obj.weight.data.detach().clone())
RuntimeError: The size of tensor a (16) must match the size of tensor b (128) at non-singleton dimension 1
[2024-01-02 11:16:17,511] [INFO] [RANK 0] replacing layer 0 cross attention with lora
INFO:sat:[RANK 0] replacing layer 0 cross attention with lora
Traceback (most recent call last):
  File "finetune_demo/finetune_cogagent_demo.py", line 266, in <module>
    model.add_mixin("lora", LoraMixin(args.num_layers, args.lora_rank, layer_range=args.layer_range), reinit=True)
  File "/opt/conda/lib/python3.8/site-packages/sat/model/base_model.py", line 122, in add_mixin
    new_mixin.reinit(self)  # also pass current mixins
  File "/opt/conda/lib/python3.8/site-packages/sat/model/finetune/lora2.py", line 195, in reinit
    parent_model.transformer.layers[i].cross_attention.dense = replace_linear_with_lora(parent_model.transformer.layers[i].cross_attention.dense, 1, self.r, self.lora_alpha, self.lora_dropout, qlora=self.qlora)
  File "/opt/conda/lib/python3.8/site-packages/sat/model/finetune/lora2.py", line 140, in replace_linear_with_lora
    new_layer = LoraLinear(original_cls, partition, in_dim, out_dim, r, *args, **kw_args, original_obj=lin)
  File "/opt/conda/lib/python3.8/site-packages/sat/model/finetune/lora2.py", line 93, in __init__
    self.original.weight.data.copy_(original_obj.weight.data.detach().clone())
RuntimeError: The size of tensor a (16) must match the size of tensor b (128) at non-singleton dimension 1
```

### Expected behavior / 期待表现

首先感谢您出色的工作！
针对上述报错，请问：
1. 同样的设置，为什么CogVLM微调并不会出现这个问题，但是CogAgent会出现，报错信息中的16和128分别是什么意思呢？
2. 为了使MP_SIZE=8时可以跑起来，我应该采取什么措施呢？

期待回复！

**Comment by 1049451037** [comment]
如果你想加载你训好的checkpoint继续训，只能把FineTuneTrainCogAgentModel换成FineTuneTestCogAgentModel。

**Comment by VittorioDong** [comment]
> 如果你想加载你训好的checkpoint继续训，只能把FineTuneTrainCogAgentModel换成FineTuneTestCogAgentModel，并去掉下面的add mixin代码。
> 
> 正常加载原始CogAgent模型应该是没问题的。

感谢回复！
但是我是在加载原始CogAgent模型出现了下面的问题：RuntimeError: The size of tensor a (16) must match the size of tensor b (128) at non-singleton dimension 1。
这个问题是在执行[2024-01-02 11:16:16,518] [INFO] [RANK 0] replacing layer 0 attention with lora时出现的，并且Error中的16和128是8倍的关系，我将MP_SIZE换成4的时候是4倍的关系，所以我推测这个错误应该和MP_SIZE有关，我该怎么解决呢？

**Comment by zRzRzRzRzRzRzR** [comment]
或许可以在这里进行讨论 #270

**Comment by zodiacg** [comment]
遇到了相同的问题。model parallel之后参数被拆分了，导致参数拷贝时没对齐形状。但我也没理解为什么CogVLM可以而CogAgent不行
