### ISSUE TITLE
部署完成无法进行对话，回复 Model: 'HOME'

### ISSUE THREAD

**Issue by FFFFFFpy** [THUDM/CogVLM#275]
### System Info / 系統信息

 NVIDIA-SMI 536.99                 Driver Version: 536.99       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090      WDDM  | 00000000:01:00.0  On |                  Off |
| 43%   36C    P8              16W / 450W |  11864MiB / 24564MiB |      2%      Default |
|                                         |                      |                  N/A

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

[2024-01-03 15:53:54,214] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-01-03 15:53:54,573] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
Please 'pip install apex'
bin C:\MiniConda3\envs\cogvlm\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll
[2024-01-03 15:53:59,542] [INFO] building CogVLMModel model ...
[2024-01-03 15:53:59,554] [INFO] [RANK 0] > initializing model parallel with size 1
[2024-01-03 15:53:59,555] [INFO] [RANK 0] You didn't pass in LOCAL_WORLD_SIZE environment variable. We use the guessed LOCAL_WORLD_SIZE=1. If this is wrong, please pass the LOCAL_WORLD_SIZE manually.
[2024-01-03 15:53:59,557] [INFO] [RANK 0] You are using model-only mode.
For torch.distributed users or loading model parallel models, set environment variables RANK, WORLD_SIZE and LOCAL_RANK.
[2024-01-03 15:54:06,509] [INFO] [RANK 0]  > number of parameters on model parallel rank 0: 17639685376
[2024-01-03 15:54:15,816] [INFO] [RANK 0] global rank 0 is loading checkpoint C:\E\CogVLM\cogvlm-chat-v1.1\cogvlm-chat-v1.1\1\mp_rank_00_model_states.pt
[2024-01-03 15:57:08,150] [INFO] [RANK 0] > successfully loaded C:\E\CogVLM\cogvlm-chat-v1.1\cogvlm-chat-v1.1\1\mp_rank_00_model_states.pt
[Language processor version]: chat_old
[2024-01-03 15:57:11,850] [INFO] [RANK 0] > Quantizing model weight to 4 bits
[2024-01-03 15:58:36,849] [INFO] [RANK 0] > Quantized 17360486400 parameters in total.
Welcome to CogAgent-CLI. Enter an image URL or local file path to load an image. Continue inputting text to engage in a conversation. Type "clear" to start over, or "stop" to end the program.
Please enter the image path or URL: C:\E\test1.png
User: Please describe the image
Model: 'HOME'
Please enter the image path or URL:

### Expected behavior / 期待表现

我以为我部署完成了，但是无论我上传什么图片上去，问它问题，它只会回复Model: 'HOME'

**Comment by 1049451037** [comment]
把这里的try except注释掉，查看更完整的报错信息：

https://github.com/THUDM/CogVLM/blob/390b7c6aad7381597cce4403f7d05c1874369a84/basic_demo/cli_demo_sat.py#L118-L137

**Comment by FFFFFFpy** [comment]
注释以后，连 Model: 'HOME'都没了，也没有其他报错信息。只有User:

**Comment by 1049451037** [comment]
我是说只注释try和except两行，不是注释一整段……

**Comment by FFFFFFpy** [comment]
![image](https://github.com/THUDM/CogVLM/assets/87560048/604afab5-bfa5-49e2-9190-708428ef0cec)
![image](https://github.com/THUDM/CogVLM/assets/87560048/46eff6fe-73aa-4d51-bde0-c8630c9756e6)

**Comment by 1049451037** [comment]
把中间那一段往左缩进一下，不然就跑到上面的if里去了……

**Comment by FFFFFFpy** [comment]
[2024-01-03 17:06:02,426] [INFO] [RANK 0] You didn't pass in LOCAL_WORLD_SIZE environment variable. We use the guessed LOCAL_WORLD_SIZE=1. If this is wrong, please pass the LOCAL_WORLD_SIZE manually.
[2024-01-03 17:06:02,428] [INFO] [RANK 0] You are using model-only mode.
For torch.distributed users or loading model parallel models, set environment variables RANK, WORLD_SIZE and LOCAL_RANK.
[2024-01-03 17:06:09,302] [INFO] [RANK 0]  > number of parameters on model parallel rank 0: 17639685376
[2024-01-03 17:06:20,791] [INFO] [RANK 0] global rank 0 is loading checkpoint C:\E\CogVLM\cogvlm-chat-v1.1\cogvlm-chat-v1.1\1\mp_rank_00_model_states.pt
[2024-01-03 17:08:42,631] [INFO] [RANK 0] > successfully loaded C:\E\CogVLM\cogvlm-chat-v1.1\cogvlm-chat-v1.1\1\mp_rank_00_model_states.pt
[Language processor version]: chat_old
[2024-01-03 17:08:45,565] [INFO] [RANK 0] > Quantizing model weight to 4 bits
[2024-01-03 17:09:44,614] [INFO] [RANK 0] > Quantized 17360486400 parameters in total.
Welcome to CogAgent-CLI. Enter an image URL or local file path to load an image. Continue inputting text to engage in a conversation. Type "clear" to start over, or "stop" to end the program.
Please enter the image path or URL: c:\E\test1.png
User: please describe the image
Model: Traceback (most recent call last):
  File "C:\E\CogVLM\basic_demo\cli_demo_sat.py", line 161, in <module>
    main()
  File "C:\E\CogVLM\basic_demo\cli_demo_sat.py", line 119, in main
    response, history, cache_image = chat(
  File "C:\E\CogVLM\utils\utils\chat.py", line 108, in chat
    for tokens, mems in filling_stream:
  File "C:\MiniConda3\envs\cogvlm\lib\site-packages\sat\generation\autoregressive_sampling.py", line 203, in stream_filling_sequence
    logits, *output_per_layers = model(
  File "C:\MiniConda3\envs\cogvlm\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\MiniConda3\envs\cogvlm\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\E\CogVLM\utils\models\cogvlm_model.py", line 119, in forward
    return super().forward(input_ids=input_ids, vision_expert_mask=vision_expert_mask, image_embed_mask=image_embed_mask, **kwargs)
  File "C:\MiniConda3\envs\cogvlm\lib\site-packages\sat\model\base_model.py", line 137, in forward
    return self.transformer(*args, **kwargs)
  File "C:\MiniConda3\envs\cogvlm\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\MiniConda3\envs\cogvlm\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\MiniConda3\envs\cogvlm\lib\site-packages\sat\model\transformer.py", line 645, in forward
    layer_ret = layer(*args, layer_id=torch.tensor(i), **kw_args, position_ids=position_ids, **output_cross_layer,
  File "C:\MiniConda3\envs\cogvlm\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\MiniConda3\envs\cogvlm\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\MiniConda3\envs\cogvlm\lib\site-packages\sat\model\transformer.py", line 370, in forward
    return HOOKS_DEFAULT['layer_forward'](self, hidden_states, mask, *args, **kw_args)
  File "C:\MiniConda3\envs\cogvlm\lib\site-packages\sat\transformer_defaults.py", line 164, in layer_forward_default
    attention_output = self.attention(attention_input, mask, **kw_args)
  File "C:\MiniConda3\envs\cogvlm\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\MiniConda3\envs\cogvlm\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\MiniConda3\envs\cogvlm\lib\site-packages\sat\model\transformer.py", line 111, in forward
    return self.hooks['attention_forward'](hidden_states, mask, **kw_args)
  File "C:\E\CogVLM\utils\models\mixin.py", line 247, in attention_forward
    query_layer, key_layer = mixin_self.rotary_emb(query_layer,key_layer, kw_args['position_ids'], max_seqlen=kw_args['position_ids'].max()+1, layer_id=kw_args['layer_id'])
  File "C:\MiniConda3\envs\cogvlm\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\MiniConda3\envs\cogvlm\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\MiniConda3\envs\cogvlm\lib\site-packages\sat\model\position_embedding\triton_rotary_embeddings.py", line 245, in forward
    q = apply_rotary_emb_func(
  File "C:\MiniConda3\envs\cogvlm\lib\site-packages\sat\model\position_embedding\triton_rotary_embeddings.py", line 99, in apply_rotary_emb
    return ApplyRotaryEmb.apply(
  File "C:\MiniConda3\envs\cogvlm\lib\site-packages\torch\autograd\function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\MiniConda3\envs\cogvlm\lib\site-packages\sat\model\position_embedding\triton_rotary_embeddings.py", line 25, in forward
    out = apply_rotary(
  File "C:\MiniConda3\envs\cogvlm\lib\site-packages\sat\model\position_embedding\triton_rotary.py", line 212, in apply_rotary
    rotary_kernel[grid](
  File "C:\MiniConda3\envs\cogvlm\lib\site-packages\triton\runtime\jit.py", line 106, in launcher
    return self.run(*args, grid=grid, **kwargs)
  File "<string>", line 41, in rotary_kernel
  File "C:\MiniConda3\envs\cogvlm\lib\site-packages\triton\compiler.py", line 1230, in compile
    so_cache_manager = CacheManager(so_cache_key)
  File "C:\MiniConda3\envs\cogvlm\lib\site-packages\triton\compiler.py", line 1102, in __init__
    self.cache_dir = os.environ.get('TRITON_CACHE_DIR', default_cache_dir())
  File "C:\MiniConda3\envs\cogvlm\lib\site-packages\triton\compiler.py", line 1093, in default_cache_dir
    return os.path.join(os.environ["HOME"], ".triton", "cache")
  File "C:\MiniConda3\envs\cogvlm\lib\os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'

**Comment by 1049451037** [comment]
如果您的电脑无法安装triton，可以使用cli_demo_hf.py，huggingface版本不依赖于triton。

**Comment by FFFFFFpy** [comment]
torch-2.1.2+cu118-cp310-cp310-win_amd64
torchvision-0.16.2+cu118-cp310-cp310-win_amd64
triton-2.0.0-cp310-cp310-win_amd64
xformers-0.0.23.post1+cu118-cp310-cp310-win_amd64
emmmm用不了么？hf版好像没法用webui

**Comment by 1049451037** [comment]
如果看报错的话是缺少HOME环境变量，可以搜索一下windows怎么配置环境变量，很简单，增加一下HOME对应的位置就好了。

**Comment by zRzRzRzRzRzRzR** [comment]
any question about finetune can discussion #270 here
