### ISSUE TITLE
启动basic_demo/web_demo.py抱：ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)

### ISSUE THREAD

**Issue by JustinZou** [THUDM/CogVLM#290]
### System Info / 系統信息

启动web版的demo，报如下错误：
(cogvlm) ubuntu@tokyo-a10-1:~/ChatGPT/CogVLM/basic_demo$ python web_demo.py --from_pretrained=/home/ubuntu/ChatGPT/Models/THUDM/cogagent-chat-hf --version chat --quant 4
[2024-01-06 07:38:03,708] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/home/ubuntu/ChatGPT/CogVLM/basic_demo/web_demo.py", line 23, in <module>
    from sat.model.mixins import CachedAutoregressiveMixin
  File "/home/ubuntu/anaconda3/envs/cogvlm/lib/python3.11/site-packages/sat/__init__.py", line 3, in <module>
    from .model import AutoModel
  File "/home/ubuntu/anaconda3/envs/cogvlm/lib/python3.11/site-packages/sat/model/__init__.py", line 1, in <module>
    from .base_model import BaseModel, BaseMixin, AutoModel, get_model
  File "/home/ubuntu/anaconda3/envs/cogvlm/lib/python3.11/site-packages/sat/model/base_model.py", line 21, in <module>
    from sat.model.transformer import BaseTransformer, standard_attention
  File "/home/ubuntu/anaconda3/envs/cogvlm/lib/python3.11/site-packages/sat/model/transformer.py", line 29, in <module>
    from sat.ops.layernorm import LayerNorm
  File "/home/ubuntu/anaconda3/envs/cogvlm/lib/python3.11/site-packages/sat/ops/layernorm.py", line 2, in <module>
    from apex.normalization.fused_layer_norm import FusedLayerNorm
  File "/home/ubuntu/anaconda3/envs/cogvlm/lib/python3.11/site-packages/apex/__init__.py", line 13, in <module>
    from pyramid.session import UnencryptedCookieSessionFactoryConfig
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)
(cogvlm) ubuntu@tokyo-a10-1:~/ChatGPT/CogVLM/basic_demo$ 

下面是CUDA版本信息：
![image](https://github.com/THUDM/CogVLM/assets/6497081/16e1cac2-8909-4037-b964-de2134ffa2e1)

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

启动web版的demo，报如下错误：
(cogvlm) ubuntu@tokyo-a10-1:~/ChatGPT/CogVLM/basic_demo$ python web_demo.py --from_pretrained=/home/ubuntu/ChatGPT/Models/THUDM/cogagent-chat-hf --version chat --quant 4
[2024-01-06 07:38:03,708] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/home/ubuntu/ChatGPT/CogVLM/basic_demo/web_demo.py", line 23, in <module>
    from sat.model.mixins import CachedAutoregressiveMixin
  File "/home/ubuntu/anaconda3/envs/cogvlm/lib/python3.11/site-packages/sat/__init__.py", line 3, in <module>
    from .model import AutoModel
  File "/home/ubuntu/anaconda3/envs/cogvlm/lib/python3.11/site-packages/sat/model/__init__.py", line 1, in <module>
    from .base_model import BaseModel, BaseMixin, AutoModel, get_model
  File "/home/ubuntu/anaconda3/envs/cogvlm/lib/python3.11/site-packages/sat/model/base_model.py", line 21, in <module>
    from sat.model.transformer import BaseTransformer, standard_attention
  File "/home/ubuntu/anaconda3/envs/cogvlm/lib/python3.11/site-packages/sat/model/transformer.py", line 29, in <module>
    from sat.ops.layernorm import LayerNorm
  File "/home/ubuntu/anaconda3/envs/cogvlm/lib/python3.11/site-packages/sat/ops/layernorm.py", line 2, in <module>
    from apex.normalization.fused_layer_norm import FusedLayerNorm
  File "/home/ubuntu/anaconda3/envs/cogvlm/lib/python3.11/site-packages/apex/__init__.py", line 13, in <module>
    from pyramid.session import UnencryptedCookieSessionFactoryConfig
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)
(cogvlm) ubuntu@tokyo-a10-1:~/ChatGPT/CogVLM/basic_demo$ 

下面是CUDA版本信息：
![image](https://github.com/THUDM/CogVLM/assets/6497081/16e1cac2-8909-4037-b964-de2134ffa2e1)

### Expected behavior / 期待表现

希望能正常运行web_demo.py

**Comment by darkacorn** [comment]
wont fit in 24g even with bnb 4 bit

**Comment by zRzRzRzRzRzRzR** [comment]
内存要按照fp16来分配，但是转换为推理的时候显存占用为4bit的显存，这是huggingface的，只推理的话可以试试hf的模型
