### ISSUE TITLE
error when  CUDA_VISIBLE_DEVICES=1,3 torchrun --standalone --nnodes=1 --nproc-per-node=2 cli_demo_sat.py --from_pretrained cogagent-chat --version chat --bf16

### ISSUE THREAD

**Issue by skyfallsss** [THUDM/CogVLM#293]
[2024-01-07 12:20:59,553] torch.distributed.run: [WARNING] master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
[2024-01-07 12:20:59,554] torch.distributed.run: [WARNING] 
[2024-01-07 12:20:59,554] torch.distributed.run: [WARNING] *****************************************
[2024-01-07 12:20:59,554] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2024-01-07 12:20:59,554] torch.distributed.run: [WARNING] *****************************************
[2024-01-07 12:21:02,340] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-01-07 12:21:02,694] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.2+cu121 with CUDA 1201 (you have 2.1.2)
    Python  3.8.18 (you have 3.8.16)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Please 'pip install apex'
[2024-01-07 12:21:06,909] [INFO] building CogAgentModel model ...
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.2+cu121 with CUDA 1201 (you have 2.1.2)
    Python  3.8.18 (you have 3.8.16)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Please 'pip install apex'
[2024-01-07 12:21:07,834] [INFO] building CogAgentModel model ...
[2024-01-07 12:21:07,841] [INFO] [RANK 0] > initializing model parallel with size 2
[2024-01-07 12:21:07,842] [INFO] [RANK 0] You are using model-only mode.
For torch.distributed users or loading model parallel models, set environment variables RANK, WORLD_SIZE and LOCAL_RANK.
[2024-01-07 12:21:41,320] [INFO] [RANK 0]  > number of parameters on model parallel rank 0: 9376828736
INFO:sat:[RANK 0]  > number of parameters on model parallel rank 0: 9376828736
[2024-01-07 12:21:47,852] [INFO] [RANK 1]  > number of parameters on model parallel rank 1: 9376828736
INFO:sat:[RANK 1]  > number of parameters on model parallel rank 1: 9376828736
[2024-01-07 12:21:49,995] [INFO] [RANK 0] > initializing model parallel with size 1
INFO:sat:[RANK 0] > initializing model parallel with size 1
[2024-01-07 12:21:49,998] [INFO] [RANK 0] building CogAgentModel model ...
INFO:sat:[RANK 0] building CogAgentModel model ...
[2024-01-07 12:22:18,583] [INFO] [RANK 0]  > number of parameters on model parallel rank 0: 18291033280
INFO:sat:[RANK 0]  > number of parameters on model parallel rank 0: 18291033280
[2024-01-07 12:22:35,510] [INFO] [RANK 0] global rank 0 is loading checkpoint /data/home/cuitor/.sat_models/cogagent-chat/1/mp_rank_00_model_states.pt
INFO:sat:[RANK 0] global rank 0 is loading checkpoint /data/home/cuitor/.sat_models/cogagent-chat/1/mp_rank_00_model_states.pt
[2024-01-07 12:23:06,039] [INFO] [RANK 0] > successfully loaded /data/home/cuitor/.sat_models/cogagent-chat/1/mp_rank_00_model_states.pt
INFO:sat:[RANK 0] > successfully loaded /data/home/cuitor/.sat_models/cogagent-chat/1/mp_rank_00_model_states.pt
[2024-01-07 12:23:07,926] [INFO] [RANK 0] > initializing model parallel with size 2
INFO:sat:[RANK 0] > initializing model parallel with size 2
[W ProcessGroupNCCL.cpp:1856] Warning: 0NCCL_AVOID_RECORD_STREAMS=1 has no effect for point-to-point collectives. (function operator())
[W ProcessGroupNCCL.cpp:1856] Warning: 0NCCL_AVOID_RECORD_STREAMS=1 has no effect for point-to-point collectives. (function operator())
[Language processor version]: chat
Traceback (most recent call last):
  File "cli_demo_sat.py", line 161, in <module>
    main()
  File "cli_demo_sat.py", line 56, in main
    tokenizer = llama2_tokenizer(args.local_tokenizer, signal_type=language_processor_version)
  File "/data/home/cuitor/skyfall/CogVLM/utils/utils/language.py", line 42, in llama2_tokenizer
    tokenizer = LlamaTokenizer.from_pretrained(tokenizer_path)
  File "/data/home/cuitor/anaconda3/envs/sam/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2012, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'lmsys/vicuna-7b-v1.5'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'lmsys/vicuna-7b-v1.5' is the correct path to a directory containing all relevant files for a LlamaTokenizer tokenizer.
[Language processor version]: chat
Traceback (most recent call last):
  File "cli_demo_sat.py", line 161, in <module>
    main()
  File "cli_demo_sat.py", line 56, in main
    tokenizer = llama2_tokenizer(args.local_tokenizer, signal_type=language_processor_version)
  File "/data/home/cuitor/skyfall/CogVLM/utils/utils/language.py", line 42, in llama2_tokenizer
    tokenizer = LlamaTokenizer.from_pretrained(tokenizer_path)
  File "/data/home/cuitor/anaconda3/envs/sam/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2012, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'lmsys/vicuna-7b-v1.5'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'lmsys/vicuna-7b-v1.5' is the correct path to a directory containing all relevant files for a LlamaTokenizer tokenizer.
[2024-01-07 12:23:55,100] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 2614149 closing signal SIGTERM
[2024-01-07 12:23:55,164] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 1 (pid: 2614153) of binary: /data/home/cuitor/anaconda3/envs/sam/bin/python
Traceback (most recent call last):
  File "/data/home/cuitor/anaconda3/envs/sam/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.1.2', 'console_scripts', 'torchrun')())
  File "/data/home/cuitor/anaconda3/envs/sam/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/data/home/cuitor/anaconda3/envs/sam/lib/python3.8/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/data/home/cuitor/anaconda3/envs/sam/lib/python3.8/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/data/home/cuitor/anaconda3/envs/sam/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/home/cuitor/anaconda3/envs/sam/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
cli_demo_sat.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-01-07_12:23:55
  host      : 1x5aaa7bdp29nk
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2614153)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by skyfallsss** [comment]
how to download the  lmsys/vicuna-7b-v1.5 manually

**Comment by zRzRzRzRzRzRzR** [comment]
go to huggingface and pull manually
