### ISSUE TITLE
Error when run `python openai_api.py` under RTX4090

### ISSUE THREAD

**Issue by danbao** [THUDM/CogVLM#296]
### System Info / 系統信息

<img width="732" alt="image" src="https://github.com/THUDM/CogVLM/assets/4090783/523e940b-773d-49a5-9df9-1b623299fadb">

NVIDIA-SMI 535.129.03             
Driver Version: 535.98       
CUDA Version: 12.2
Transformers Version: 4.36.2
Python 3.10.12
Linux DESKTOP-FH3CGQ7 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

commitId
1d9295a003bbc3a29ef5b1d74904b92cdbd8c029

### Who can help? / 谁可以帮助到您？

@zr

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. python -m venv cogvlm
2. source cogvlm/bin/activate
3. pip install -r requirements.txt 
```bash
Successfully installed MarkupSafe-2.1.3 SwissArmyTransformer-0.4.9 accelerate-0.25.0 aiohttp-3.9.1 aiosignal-1.3.1 altair-5.2.0 annotated-types-0.6.0 anyio-4.2.0 async-timeout-4.0.3 attrs-23.2.0 blinker-1.7.0 blis-0.7.11 boto3-1.34.14 botocore-1.34.14 braceexpand-0.1.7 cachetools-5.3.2 catalogue-2.0.10 certifi-2023.11.17 charset-normalizer-3.3.2 click-8.1.7 cloudpathlib-0.16.0 confection-0.1.4 contourpy-1.2.0 cpm-kernels-1.0.11 cycler-0.12.1 cymem-2.0.8 datasets-2.16.1 deepspeed-0.12.6 dill-0.3.7 distro-1.9.0 einops-0.7.0 exceptiongroup-1.2.0 fastapi-0.108.0 filelock-3.13.1 fonttools-4.47.0 frozenlist-1.4.1 fsspec-2023.10.0 gitdb-4.0.11 gitpython-3.1.40 h11-0.14.0 hjson-3.1.0 httpcore-1.0.2 httpx-0.26.0 huggingface-hub-0.20.2 idna-3.6 importlib-metadata-6.11.0 jinja2-3.1.2 jmespath-1.0.1 jsonschema-4.20.0 jsonschema-specifications-2023.12.1 kiwisolver-1.4.5 langcodes-3.3.0 loguru-0.7.2 markdown-it-py-3.0.0 matplotlib-3.8.2 mdurl-0.1.2 mpmath-1.3.0 multidict-6.0.4 multiprocess-0.70.15 murmurhash-1.0.10 networkx-3.2.1 ninja-1.11.1.1 numpy-1.26.3 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.18.1 nvidia-nvjitlink-cu12-12.3.101 nvidia-nvtx-cu12-12.1.105 openai-1.6.1 packaging-23.2 pandas-2.1.4 pillow-10.2.0 preshed-3.0.9 protobuf-4.25.1 psutil-5.9.7 py-cpuinfo-9.0.0 pyarrow-14.0.2 pyarrow-hotfix-0.6 pydantic-2.5.3 pydantic-core-2.14.6 pydeck-0.8.1b0 pygments-2.17.2 pynvml-11.5.0 pyparsing-3.1.1 python-dateutil-2.8.2 pytz-2023.3.post1 pyyaml-6.0.1 referencing-0.32.1 regex-2023.12.25 requests-2.31.0 rich-13.7.0 rpds-py-0.16.2 s3transfer-0.10.0 safetensors-0.4.1 seaborn-0.13.1 sentencepiece-0.1.99 six-1.16.0 smart-open-6.4.0 smmap-5.0.1 sniffio-1.3.0 spacy-3.7.2 spacy-legacy-3.0.12 spacy-loggers-1.0.5 srsly-2.4.8 sse-starlette-1.8.2 starlette-0.32.0.post1 streamlit-1.29.0 sympy-1.12 tenacity-8.2.3 tensorboardX-2.6.2.2 thinc-8.2.2 timm-0.9.12 tokenizers-0.15.0 toml-0.10.2 toolz-0.12.0 torch-2.1.2 torchvision-0.16.2 tornado-6.4 tqdm-4.66.1 transformers-4.36.2 triton-2.1.0 typer-0.9.0 typing-extensions-4.9.0 tzdata-2023.4 tzlocal-5.2 urllib3-2.0.7 uvicorn-0.24.0.post1 validators-0.22.0 wasabi-1.1.2 watchdog-3.0.0 weasel-0.3.4 webdataset-0.2.86 xformers-0.0.23.post1 xxhash-3.4.1 yarl-1.9.4 zipp-3.17.0

[notice] A new release of pip is available: 23.0.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
```
4.  pip install bitsandbytes (due below error)
```bash
python openai_api.py
========Use torch type as:torch.bfloat16 with device:cuda========


Please 'pip install apex'
Traceback (most recent call last):
  File "/mnt/c/workspace/CogVLM/openai_demo/openai_api.py", line 382, in <module>
    model = AutoModelForCausalLM.from_pretrained(
  File "/mnt/c/workspace/CogVLM/openai_demo/cogvlm/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "/mnt/c/workspace/CogVLM/openai_demo/cogvlm/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2876, in from_pretrained
    quantization_config, kwargs = BitsAndBytesConfig.from_dict(
  File "/mnt/c/workspace/CogVLM/openai_demo/cogvlm/lib/python3.10/site-packages/transformers/utils/quantization_config.py", line 89, in from_dict
    config = cls(**config_dict)
  File "/mnt/c/workspace/CogVLM/openai_demo/cogvlm/lib/python3.10/site-packages/transformers/utils/quantization_config.py", line 233, in __init__
    self.post_init()
  File "/mnt/c/workspace/CogVLM/openai_demo/cogvlm/lib/python3.10/site-packages/transformers/utils/quantization_config.py", line 259, in post_init
    if self.load_in_4bit and not version.parse(importlib.metadata.version("bitsandbytes")) >= version.parse(
  File "/root/miniconda3/lib/python3.10/importlib/metadata/__init__.py", line 996, in version
    return distribution(distribution_name).version
  File "/root/miniconda3/lib/python3.10/importlib/metadata/__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "/root/miniconda3/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for bitsandbytes
```

5. cd openai_demo && `python openai_api.py`  (success loading checkpoint )
6. open another terminal `python openai_api_request.py`  (receive `Error: 500` from openai-demo side)

then report
```bash
python openai_api.py
========Use torch type as:torch.bfloat16 with device:cuda========


Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:26<00:00,  3.29s/it]
INFO:     Started server process [394922]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2024-01-08 14:56:37.932 | DEBUG    | __main__:generate_stream_cogvlm:310 - ==== request ====
Do you think this is a spring or winter photo?
INFO:     127.0.0.1:54408 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/root/miniconda3/lib/python3.10/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/root/miniconda3/lib/python3.10/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/root/miniconda3/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/mnt/c/workspace/CogVLM/openai_demo/openai_api.py", line 174, in create_chat_completion
    response = generate_cogvlm(model, tokenizer, gen_params)
  File "/mnt/c/workspace/CogVLM/openai_demo/openai_api.py", line 238, in generate_cogvlm
    for response in generate_stream_cogvlm(model, tokenizer, params):
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/mnt/c/workspace/CogVLM/openai_demo/openai_api.py", line 343, in generate_stream_cogvlm
    model.generate(**inputs, **gen_kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 1764, in generate
    return self.sample(
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2861, in sample
    outputs = self(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/cogvlm-chat-hf/e29dc3ba206d524bf8efbfc60d80fc4556ab0e3c/modeling_cogvlm.py", line 660, in forward
    outputs = self.model(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/cogvlm-chat-hf/e29dc3ba206d524bf8efbfc60d80fc4556ab0e3c/modeling_cogvlm.py", line 428, in forward
    images_features = self.encode_images(images)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/cogvlm-chat-hf/e29dc3ba206d524bf8efbfc60d80fc4556ab0e3c/modeling_cogvlm.py", line 400, in encode_images
    images_features = self.vision(images)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/cogvlm-chat-hf/e29dc3ba206d524bf8efbfc60d80fc4556ab0e3c/visual.py", line 128, in forward
    x = self.patch_embedding(images)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/cogvlm-chat-hf/e29dc3ba206d524bf8efbfc60d80fc4556ab0e3c/visual.py", line 16, in forward
    x = self.proj(images)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: GET was unable to find an engine to execute this computation
```

### Expected behavior / 期待表现

success return right response

**Comment by zRzRzRzRzRzRzR** [comment]
Just run and get 500？
do you sent base64 of pic？

**Comment by danbao** [comment]
> Just run and get 500？
yes
do you sent base64 of pic？
yes, I print the message in console and the request include
`'image_url': {'url': 'data:image/jpeg;base64,/9j/4gIcSUNDX1BST0ZJ` 
<img width="1704" alt="image" src="https://github.com/THUDM/CogVLM/assets/4090783/70845189-5621-47ec-90d2-479358465341">

**Comment by danbao** [comment]
I modified the model to `THUDM/cogagent-chat-hf` still received the same error.

```bash
python openai_api.py
========Use torch type as:torch.bfloat16 with device:cuda========


A new version of the following files was downloaded from https://huggingface.co/THUDM/cogagent-chat-hf:
- configuration_cogagent.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
modeling_cogagent.py: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 42.5k/42.5k [00:00<00:00, 353MB/s]
cross_visual.py: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32.6k/32.6k [00:00<00:00, 4.49MB/s]
A new version of the following files was downloaded from https://huggingface.co/THUDM/cogagent-chat-hf:
- cross_visual.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
visual.py: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5.45k/5.45k [00:00<00:00, 72.1MB/s]
A new version of the following files was downloaded from https://huggingface.co/THUDM/cogagent-chat-hf:
- visual.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
A new version of the following files was downloaded from https://huggingface.co/THUDM/cogagent-chat-hf:
- modeling_cogagent.py
- cross_visual.py
- visual.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
Please 'pip install apex'
Downloading shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  2.87it/s]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:31<00:00,  3.88s/it]
Some weights of CogAgentForCausalLM were not initialized from the model checkpoint at THUDM/cogagent-chat-hf and are newly initialized: ['model.cross_vision.vit.model.blocks.13.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.6.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.0.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.5.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.7.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.2.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.6.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.3.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.12.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.4.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.10.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.5.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.15.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.16.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.7.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.17.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.4.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.18.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.8.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.15.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.1.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.16.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.20.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.22.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.12.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.21.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.14.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.8.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.19.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.13.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.2.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.3.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.18.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.1.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.23.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.23.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.22.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.9.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.11.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.17.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.20.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.10.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.9.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.11.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.14.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.19.attn.rope.freqs_cos', 'model.cross_vision.vit.model.blocks.0.attn.rope.freqs_sin', 'model.cross_vision.vit.model.blocks.21.attn.rope.freqs_cos']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
INFO:     Started server process [399106]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2024-01-08 15:48:18.124 | DEBUG    | __main__:generate_stream_cogvlm:310 - ==== request ====
Do you think this is a spring or winter photo?
INFO:     127.0.0.1:42908 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/miniconda3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/miniconda3/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/root/miniconda3/lib/python3.10/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/root/miniconda3/lib/python3.10/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/root/miniconda3/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/mnt/c/workspace/CogVLM/openai_demo/openai_api.py", line 174, in create_chat_completion
    response = generate_cogvlm(model, tokenizer, gen_params)
  File "/mnt/c/workspace/CogVLM/openai_demo/openai_api.py", line 238, in generate_cogvlm
    for response in generate_stream_cogvlm(model, tokenizer, params):
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/mnt/c/workspace/CogVLM/openai_demo/openai_api.py", line 343, in generate_stream_cogvlm
    model.generate(**inputs, **gen_kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 1764, in generate
    return self.sample(
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2861, in sample
    outputs = self(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/cogagent-chat-hf/d519da3b191401234f4bd86ce1c287c61bc276a3/modeling_cogagent.py", line 786, in forward
    outputs = self.model(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/cogagent-chat-hf/d519da3b191401234f4bd86ce1c287c61bc276a3/modeling_cogagent.py", line 523, in forward
    images_features = self.encode_images(images)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/cogagent-chat-hf/d519da3b191401234f4bd86ce1c287c61bc276a3/modeling_cogagent.py", line 480, in encode_images
    images_features = self.vision(images)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/cogagent-chat-hf/d519da3b191401234f4bd86ce1c287c61bc276a3/visual.py", line 129, in forward
    x = self.patch_embedding(images)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/cogagent-chat-hf/d519da3b191401234f4bd86ce1c287c61bc276a3/visual.py", line 16, in forward
    x = self.proj(images)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: GET was unable to find an engine to execute this computation
```

**Comment by zRzRzRzRzRzRzR** [comment]
I will check

**Comment by danbao** [comment]
After removing Miniconda and reinstalling Python and pip, the problem has been resolved. Thank you for your assistance.
