### ISSUE TITLE
RuntimeError: No backend type associated with device type cpu

### ISSUE THREAD

**Issue by mshumer** [THUDM/CogVLM#328]
### System Info / 系統信息

I'm getting this error when fine-tuning, which hasn't happened before -- always using the same machine setup, so this is weird to see:
```
603760c1c291:16957:18841 [8] NCCL INFO threadThresholds 8/8/64 | 80/8/64 | 512 | 512
603760c1c291:16957:18841 [8] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
603760c1c291:16956:18844 [7] NCCL INFO comm 0x55dbf256d2a0 rank 7 nranks 10 cudaDev 7 busId d2000 commId 0x714dd0f00c283118 - Init COMPLETE
603760c1c291:16955:18846 [6] NCCL INFO comm 0x55ef45074ff0 rank 6 nranks 10 cudaDev 6 busId d1000 commId 0x714dd0f00c283118 - Init COMPLETE
603760c1c291:16957:18841 [8] NCCL INFO comm 0x5602d468c540 rank 8 nranks 10 cudaDev 8 busId d5000 commId 0x714dd0f00c283118 - Init COMPLETE
603760c1c291:16949:18839 [0] NCCL INFO comm 0x55a3e20fdbf0 rank 0 nranks 10 cudaDev 0 busId 4f000 commId 0x714dd0f00c283118 - Init COMPLETE
603760c1c291:16952:18848 [3] NCCL INFO comm 0x55bd52ef2400 rank 3 nranks 10 cudaDev 3 busId 56000 commId 0x714dd0f00c283118 - Init COMPLETE
603760c1c291:16954:18843 [5] NCCL INFO comm 0x557ae15cd3c0 rank 5 nranks 10 cudaDev 5 busId ce000 commId 0x714dd0f00c283118 - Init COMPLETE
603760c1c291:16958:18845 [9] NCCL INFO comm 0x558aeb5efcc0 rank 9 nranks 10 cudaDev 9 busId d6000 commId 0x714dd0f00c283118 - Init COMPLETE
603760c1c291:16950:18842 [1] NCCL INFO comm 0x55b0a7683d90 rank 1 nranks 10 cudaDev 1 busId 52000 commId 0x714dd0f00c283118 - Init COMPLETE
603760c1c291:16951:18847 [2] NCCL INFO comm 0x5598d1860d60 rank 2 nranks 10 cudaDev 2 busId 53000 commId 0x714dd0f00c283118 - Init COMPLETE
603760c1c291:16953:18840 [4] NCCL INFO comm 0x55de4b8df280 rank 4 nranks 10 cudaDev 4 busId 57000 commId 0x714dd0f00c283118 - Init COMPLETE
Traceback (most recent call last):
Traceback (most recent call last):
  File "/workspace/CogVLM/finetune_demo/finetune_cogagent_demo.py", line 289, in <module>
    model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor, cross_image_processor), collate_fn=partial(data_collator, cross_image_processor=cross_image_processor), forward_step_eval=forward_step_eval)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 101, in training_main
    model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
  File "/workspace/CogVLM/finetune_demo/finetune_cogagent_demo.py", line 289, in <module>
    model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor, cross_image_processor), collate_fn=partial(data_collator, cross_image_processor=cross_image_processor), forward_step_eval=forward_step_eval)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 180, in setup_model_untrainable_params_and_optimizer
    dist.broadcast(
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 101, in training_main
    model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 180, in setup_model_untrainable_params_and_optimizer
    dist.broadcast(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
    work = default_pg.broadcast([tensor], opts)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: No backend type associated with device type cpu
RuntimeError: No backend type associated with device type cpu
Traceback (most recent call last):
  File "/workspace/CogVLM/finetune_demo/finetune_cogagent_demo.py", line 289, in <module>
    model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor, cross_image_processor), collate_fn=partial(data_collator, cross_image_processor=cross_image_processor), forward_step_eval=forward_step_eval)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 101, in training_main
    model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 180, in setup_model_untrainable_params_and_optimizer
    dist.broadcast(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: No backend type associated with device type cpu
Traceback (most recent call last):
  File "/workspace/CogVLM/finetune_demo/finetune_cogagent_demo.py", line 289, in <module>
    model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor, cross_image_processor), collate_fn=partial(data_collator, cross_image_processor=cross_image_processor), forward_step_eval=forward_step_eval)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 101, in training_main
    model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 180, in setup_model_untrainable_params_and_optimizer
    dist.broadcast(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: No backend type associated with device type cpu
Traceback (most recent call last):
  File "/workspace/CogVLM/finetune_demo/finetune_cogagent_demo.py", line 289, in <module>
    model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor, cross_image_processor), collate_fn=partial(data_collator, cross_image_processor=cross_image_processor), forward_step_eval=forward_step_eval)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 101, in training_main
    model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 180, in setup_model_untrainable_params_and_optimizer
    dist.broadcast(
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: No backend type associated with device type cpu
  File "/workspace/CogVLM/finetune_demo/finetune_cogagent_demo.py", line 289, in <module>
    model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor, cross_image_processor), collate_fn=partial(data_collator, cross_image_processor=cross_image_processor), forward_step_eval=forward_step_eval)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 101, in training_main
    model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
  File "/workspace/CogVLM/finetune_demo/finetune_cogagent_demo.py", line 289, in <module>
    model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor, cross_image_processor), collate_fn=partial(data_collator, cross_image_processor=cross_image_processor), forward_step_eval=forward_step_eval)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 180, in setup_model_untrainable_params_and_optimizer
    dist.broadcast(
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 101, in training_main
    model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
    work = default_pg.broadcast([tensor], opts)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 180, in setup_model_untrainable_params_and_optimizer
    dist.broadcast(
RuntimeError: No backend type associated with device type cpu
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
    work = default_pg.broadcast([tensor], opts)
Traceback (most recent call last):
  File "/workspace/CogVLM/finetune_demo/finetune_cogagent_demo.py", line 289, in <module>
    model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor, cross_image_processor), collate_fn=partial(data_collator, cross_image_processor=cross_image_processor), forward_step_eval=forward_step_eval)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 101, in training_main
    model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 180, in setup_model_untrainable_params_and_optimizer
    dist.broadcast(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: No backend type associated with device type cpu
RuntimeError: No backend type associated with device type cpu
  File "/workspace/CogVLM/finetune_demo/finetune_cogagent_demo.py", line 289, in <module>
    model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor, cross_image_processor), collate_fn=partial(data_collator, cross_image_processor=cross_image_processor), forward_step_eval=forward_step_eval)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 101, in training_main
    model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 180, in setup_model_untrainable_params_and_optimizer
    dist.broadcast(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
Traceback (most recent call last):
  File "/workspace/CogVLM/finetune_demo/finetune_cogagent_demo.py", line 289, in <module>
    model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor, cross_image_processor), collate_fn=partial(data_collator, cross_image_processor=cross_image_processor), forward_step_eval=forward_step_eval)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 101, in training_main
    model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 180, in setup_model_untrainable_params_and_optimizer
    dist.broadcast(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: No backend type associated with device type cpu
Traceback (most recent call last):
Traceback (most recent call last):
  File "/workspace/CogVLM/finetune_demo/finetune_cogagent_demo.py", line 289, in <module>
    model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor, cross_image_processor), collate_fn=partial(data_collator, cross_image_processor=cross_image_processor), forward_step_eval=forward_step_eval)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 101, in training_main
    model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 180, in setup_model_untrainable_params_and_optimizer
    dist.broadcast(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: No backend type associated with device type cpu
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: No backend type associated with device type cpu
  File "/workspace/CogVLM/finetune_demo/finetune_cogagent_demo.py", line 289, in <module>
    model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor, cross_image_processor), collate_fn=partial(data_collator, cross_image_processor=cross_image_processor), forward_step_eval=forward_step_eval)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 101, in training_main
    model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
  File "/workspace/CogVLM/finetune_demo/finetune_cogagent_demo.py", line 289, in <module>
    model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor, cross_image_processor), collate_fn=partial(data_collator, cross_image_processor=cross_image_processor), forward_step_eval=forward_step_eval)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 180, in setup_model_untrainable_params_and_optimizer
    dist.broadcast(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 101, in training_main
    model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
    work = default_pg.broadcast([tensor], opts)
Traceback (most recent call last):
  File "/workspace/CogVLM/finetune_demo/finetune_cogagent_demo.py", line 289, in <module>
    model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor, cross_image_processor), collate_fn=partial(data_collator, cross_image_processor=cross_image_processor), forward_step_eval=forward_step_eval)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 101, in training_main
    model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 180, in setup_model_untrainable_params_and_optimizer
    dist.broadcast(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: No backend type associated with device type cpu
RuntimeError: No backend type associated with device type cpu
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 180, in setup_model_untrainable_params_and_optimizer
    dist.broadcast(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: No backend type associated with device type cpu
Traceback (most recent call last):
  File "/workspace/CogVLM/finetune_demo/finetune_cogagent_demo.py", line 289, in <module>
    model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor, cross_image_processor), collate_fn=partial(data_collator, cross_image_processor=cross_image_processor), forward_step_eval=forward_step_eval)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 101, in training_main
    model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 180, in setup_model_untrainable_params_and_optimizer
    dist.broadcast(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: No backend type associated with device type cpu
Traceback (most recent call last):
  File "/workspace/CogVLM/finetune_demo/finetune_cogagent_demo.py", line 289, in <module>
    model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor, cross_image_processor), collate_fn=partial(data_collator, cross_image_processor=cross_image_processor), forward_step_eval=forward_step_eval)
Traceback (most recent call last):
  File "/workspace/CogVLM/finetune_demo/finetune_cogagent_demo.py", line 289, in <module>
    model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor, cross_image_processor), collate_fn=partial(data_collator, cross_image_processor=cross_image_processor), forward_step_eval=forward_step_eval)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 101, in training_main
    model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 180, in setup_model_untrainable_params_and_optimizer
    dist.broadcast(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: No backend type associated with device type cpu
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 101, in training_main
    model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 180, in setup_model_untrainable_params_and_optimizer
    dist.broadcast(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: No backend type associated with device type cpu
Traceback (most recent call last):
  File "/workspace/CogVLM/finetune_demo/finetune_cogagent_demo.py", line 289, in <module>
    model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor, cross_image_processor), collate_fn=partial(data_collator, cross_image_processor=cross_image_processor), forward_step_eval=forward_step_eval)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 101, in training_main
    model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 180, in setup_model_untrainable_params_and_optimizer
    dist.broadcast(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: No backend type associated with device type cpu
Traceback (most recent call last):
  File "/workspace/CogVLM/finetune_demo/finetune_cogagent_demo.py", line 289, in <module>
    model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor, cross_image_processor), collate_fn=partial(data_collator, cross_image_processor=cross_image_processor), forward_step_eval=forward_step_eval)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 101, in training_main
    model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 180, in setup_model_untrainable_params_and_optimizer
    dist.broadcast(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: No backend type associated with device type cpu
Traceback (most recent call last):
  File "/workspace/CogVLM/finetune_demo/finetune_cogagent_demo.py", line 289, in <module>
    model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor, cross_image_processor), collate_fn=partial(data_collator, cross_image_processor=cross_image_processor), forward_step_eval=forward_step_eval)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 101, in training_main
    model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
  File "/usr/local/lib/python3.10/dist-packages/sat/training/deepspeed_training.py", line 180, in setup_model_untrainable_params_and_optimizer
    dist.broadcast(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: No backend type associated with device type cpu
```

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

Run the fine-tune Agent process.

### Expected behavior / 期待表现

N/A

**Comment by StevenyzZhang** [comment]
I met this error, too. It seems that it is because of a commit from SAT last week:
https://github.com/THUDM/SwissArmyTransformer/commit/abf3a5d24090eff967c5a3777cb07380db684c1f

You might want to use an older version of SAT, or add one line in the fine-tuning code to make sure the model is on cuda.

**Comment by 1049451037** [comment]
Fixed in the latest SAT, try reinstall by git clone:

```
git clone https://github.com/THUDM/SwissArmyTransformer
cd SwissArmyTransformer
pip install . --no-deps
```
