### ISSUE TITLE
双卡不能训练的问题

### ISSUE THREAD

**Issue by elesun2018** [THUDM/CogVLM#334]
CogVLM用单机单卡可以训练，用GPU0或者GPU1都可以单独训练，但是单机双卡不同一起训练。请问可能是什么问题，test_config_bf16中train_micro_batch_size_per_gpu=2，其他文件都未作更改

NCCL_DEBUG=info SAT_HOME=/home/sfz/models/satcog1206 deepspeed --master_port 6543 finetune_demo/finetune_cogvlm_demo.py --experiment-name finetune-cogvlm --model-parallel-size 1 --mode finetune --train-iters 800 --resume-dataloader --from_pretrained /home/sfz/models/satcog1206/cogvlm-grounding-generalist --max_length 1288 --lora_rank 10 --use_lora --local_tokenizer /home/sfz/models/vicuna-7b-v1.3 --version base --train-data /home/sfz/data/archive_split/train --valid-data /home/sfz/data/archive_split/valid --distributed-backend nccl --lr-decay-style cosine --warmup .02 --checkpoint-activations --vit_checkpoint_activations --save-interval 400 --eval-interval 400 --save ./checkpoints --eval-iters 10 --eval-batch-size 2 --split 1. --deepspeed_config finetune_demo/test_config_bf16.json --skip-init --seed 2023
[2024-01-18 07:09:39,971] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/sfz/soft/miniconda3/envs/test12 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/nvidia/lib64')}
  warn(msg)
/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /usr/local/nvidia/lib:/usr/local/nvidia/lib64 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0'), PosixPath('/usr/local/cuda/lib64/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
[2024-01-18 07:09:41,307] [WARNING] [runner.py:202:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2024-01-18 07:09:41,308] [INFO] [runner.py:570:main] cmd = /home/sfz/soft/miniconda3/envs/test12/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMV19 --master_addr=127.0.0.1 --master_port=6543 --enable_each_rank_log=None finetune_demo/finetune_cogvlm_demo.py --experiment-name finetune-cogvlm --model-parallel-size 1 --mode finetune --train-iters 800 --resume-dataloader --from_pretrained /home/sfz/models/satcog1206/cogvlm-grounding-generalist --max_length 1288 --lora_rank 10 --use_lora --local_tokenizer /home/sfz/models/vicuna-7b-v1.3 --version base --train-data /home/sfz/data/archive_split/train --valid-data /home/sfz/data/archive_split/valid --distributed-backend nccl --lr-decay-style cosine --warmup .02 --checkpoint-activations --vit_checkpoint_activations --save-interval 400 --eval-interval 400 --save ./checkpoints --eval-iters 10 --eval-batch-size 2 --split 1. --deepspeed_config finetune_demo/test_config_bf16.json --skip-init --seed 2023
[2024-01-18 07:09:42,207] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/sfz/soft/miniconda3/envs/test12 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/nvidia/lib64')}
  warn(msg)
/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /usr/local/nvidia/lib:/usr/local/nvidia/lib64 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so'), PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
[2024-01-18 07:09:43,321] [INFO] [launch.py:138:main] 0 NCCL_DEBUG=info
[2024-01-18 07:09:43,321] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE=libnccl-dev=2.15.5-1+cuda11.8
[2024-01-18 07:09:43,321] [INFO] [launch.py:138:main] 0 NCCL_VERSION=2.15.5-1
[2024-01-18 07:09:43,321] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE_VERSION=2.15.5-1
[2024-01-18 07:09:43,321] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE=libnccl2=2.15.5-1+cuda11.8
[2024-01-18 07:09:43,321] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE_NAME=libnccl-dev
[2024-01-18 07:09:43,321] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE_NAME=libnccl2
[2024-01-18 07:09:43,321] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE_VERSION=2.15.5-1
[2024-01-18 07:09:43,321] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0, 1]}
[2024-01-18 07:09:43,321] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=2, node_rank=0
[2024-01-18 07:09:43,321] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1]})
[2024-01-18 07:09:43,321] [INFO] [launch.py:163:main] dist_world_size=2
[2024-01-18 07:09:43,321] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0,1
[2024-01-18 07:09:44,401] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-01-18 07:09:44,401] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/sfz/soft/miniconda3/envs/test12 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/nvidia/lib64')}
  warn(msg)
/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /usr/local/nvidia/lib:/usr/local/nvidia/lib64 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so'), PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/sfz/soft/miniconda3/envs/test12 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib64'), PosixPath('/usr/local/nvidia/lib')}
  warn(msg)
/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /usr/local/nvidia/lib:/usr/local/nvidia/lib64 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so'), PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
[2024-01-18 07:09:46,977] [INFO] using world size: 2 and model-parallel size: 1 
[2024-01-18 07:09:46,977] [INFO] > padded vocab (size: 100) with 28 dummy tokens (new size: 128)
[2024-01-18 07:09:46,977] [INFO] Will override arguments with manually specified deepspeed_config!
[2024-01-18 07:09:46,988] [INFO] [RANK 0] > initializing model parallel with size 1
[2024-01-18 07:09:46,999] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-01-18 07:09:47,009] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-01-18 07:09:47,009] [INFO] [checkpointing.py:1036:_configure_using_config_file] {'partition_activations': False, 'contiguous_memory_optimization': False, 'cpu_checkpointing': False, 'number_checkpoints': None, 'synchronize_checkpoint_boundary': False, 'profile': False}
[2024-01-18 07:09:47,010] [INFO] [checkpointing.py:227:model_parallel_cuda_manual_seed] > initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 4741 and data parallel seed: 2023
[2024-01-18 07:09:47,010] [INFO] [RANK 0] building FineTuneTrainCogVLMModel model ...
[2024-01-18 07:09:52,674] [INFO] [RANK 0]  > number of parameters on model parallel rank 0: 17639685376
[2024-01-18 07:10:02,504] [INFO] [RANK 0] global rank 0 is loading checkpoint /home/sfz/models/satcog1206/cogvlm-grounding-generalist/1/mp_rank_00_model_states.pt
[2024-01-18 07:10:53,494] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 14416
[2024-01-18 07:10:53,496] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 14417
[2024-01-18 07:10:54,272] [ERROR] [launch.py:321:sigkill_handler] ['/home/sfz/soft/miniconda3/envs/test12/bin/python', '-u', 'finetune_demo/finetune_cogvlm_demo.py', '--local_rank=1', '--experiment-name', 'finetune-cogvlm', '--model-parallel-size', '1', '--mode', 'finetune', '--train-iters', '800', '--resume-dataloader', '--from_pretrained', '/home/sfz/models/satcog1206/cogvlm-grounding-generalist', '--max_length', '1288', '--lora_rank', '10', '--use_lora', '--local_tokenizer', '/home/sfz/models/vicuna-7b-v1.3', '--version', 'base', '--train-data', '/home/sfz/data/archive_split/train', '--valid-data', '/home/sfz/data/archive_split/valid', '--distributed-backend', 'nccl', '--lr-decay-style', 'cosine', '--warmup', '.02', '--checkpoint-activations', '--vit_checkpoint_activations', '--save-interval', '400', '--eval-interval', '400', '--save', './checkpoints', '--eval-iters', '10', '--eval-batch-size', '2', '--split', '1.', '--deepspeed_config', 'finetune_demo/test_config_bf16.json', '--skip-init', '--seed', '2023'] exits with return code = -9

**Comment by 1049451037** [comment]
如果想使用qlora，请先正常安装bitsandbytes。

你试一下运行python：

```python
import bitsandbytes
```

报什么错

**Comment by 1049451037** [comment]
请正确配置cuda环境变量，保证你的环境能正常运行nvcc，然后安装好ninja。多卡的时候可能会有一些算子需要编译。

**Comment by elesun2018** [comment]
日志log显示的信息太多，可以看到两个进程被kill，不知道是不是超参数设置的问题？
我的问题重点是：
CogVLM用单机单卡可以训练，用GPU0或者GPU1都可以单独训练，但是单机双卡不同一起训练。请问可能是什么问题，test_config_bf16中train_micro_batch_size_per_gpu=2，其他文件都未作更改

**Comment by 1049451037** [comment]
也有可能是你的内存不足，因为双卡可能会增大一些cpu内存的占用。

**Comment by 1049451037** [comment]
不是超参数的问题。

**Comment by 1049451037** [comment]
以及更新一下最新的sat，也会让lora默认在cuda上：

```
git clone https://github.com/THUDM/SwissArmyTransformer
cd SwissArmyTransformer
pip install . --no-deps
```

如果内存有限，只能这样精打细算省一些内存了。

**Comment by elesun2018** [comment]
谢谢

**Comment by elesun2018** [comment]
按照上述方法还是报错
![a2ed829cb793a619c0caf0e4c08e426](https://github.com/THUDM/CogVLM/assets/37207093/4889f1b6-ecdc-46c5-8119-3fc8afedcd48)
# pip install SwissArmyTransformer==0.4.11

如果是内存不足，应该会容器异常退出，python进程异常退出OOM，目前并没有这些异常。

确定报错跟源码里面batch1没关系吧
![697a8d43bd497ec552f8350f2977c01](https://github.com/THUDM/CogVLM/assets/37207093/d51a8d4e-ce95-4942-b67c-ca41a9d554a6)

**Comment by 1049451037** [comment]
batch size = 1没问题，因为inference只能是1。

**Comment by elesun2018** [comment]
OK，增加了物理内存，确实可以单机双卡训练了，谢谢！

**Comment by sungatetop** [comment]
多卡进行微调时，出现了以下问题需要怎么解决？单卡都没问题，试了手动改为cuda加载，还是出现下面问题：
return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 192.00 MiB. GPU 0 has a total capacty of 47.99 GiB of which 8.18 GiB is free. Including non-PyTorch memory, this process has 17179869184.00 GiB memory in use. Process 3637 has 17179869184.00 GiB memory in use. Of the allocated memory 36.80 GiB is allocated by PyTorch, and 1.41 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "/mnt/f/ModelData/CogVLM/finetune_cogvlm_demo.py", line 244, in <module>
    model.add_mixin("lora", LoraMixin(args.num_layers, args.lora_rank, layer_range=args.layer_range), reinit=True)
  File "/home/chenbl/miniconda3/envs/cogvlm/lib/python3.10/site-packages/sat/model/base_model.py", line 122, in add_mixin
    new_mixin.reinit(self)  # also pass current mixins
  File "/home/chenbl/miniconda3/envs/cogvlm/lib/python3.10/site-packages/sat/model/finetune/lora2.py", line 200, in reinit
    parent_model.transformer.layers[i].attention.query_key_value = replace_linear_with_lora(parent_model.transformer.layers[i].attention.query_key_value, parent_model.transformer.layers[i].attention.stride, self.r, self.lora_alpha, self.lora_dropout, qlora=self.qlora, in_size=parent_model.transformer.hidden_size, out_size=None if not parent_model.transformer.num_multi_query_heads else parent_model.transformer.layers[i].attention.inner_hidden_size + parent_model.transformer.layers[i].attention.hidden_size_per_attention_head * parent_model.transformer.layers[i].attention.num_multi_query_heads * 2)
  File "/home/chenbl/miniconda3/envs/cogvlm/lib/python3.10/site-packages/sat/model/finetune/lora2.py", line 147, in replace_linear_with_lora
    new_layer = LoraLinear(original_cls, partition, in_dim, out_dim, r, *args, **kw_args, original_obj=lin)
  File "/home/chenbl/miniconda3/envs/cogvlm/lib/python3.10/site-packages/sat/model/finetune/lora2.py", line 97, in __init__
    self.original.weight.data.copy_(original_obj.weight.data.detach().clone())
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 96.00 MiB. GPU 1 has a total capacty of 47.99 GiB of which 10.54 GiB is free. Process 3636 has 17179869184.00 GiB memory in use. Including non-PyTorch memory, this process has 17179869184.00 GiB memory in use. Of the allocated memory 34.91 GiB is allocated by PyTorch, and 962.16 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
