### ISSUE TITLE
验证码finetune自己数据集出现评估错误

### ISSUE THREAD

**Issue by elesun2018** [THUDM/CogVLM#335]
验证码finetune自己数据集出现评估错误

IndexError: The shape of the mask [4, 1249] at index 0 does not match the shape of the indexed tensor [1, 1249, 4096] at index 0

请问 dataset.py
![image](https://github.com/THUDM/CogVLM/assets/37207093/024db745-3be5-4074-bd31-d88ea4f8d0e1)

ret = {**img_dict, **text_dict, "question_id": uni_key}
如何更改实现图片问答数据训练

**Comment by chanel111** [comment]
请问你用的finetune数据集是中文的吗？

**Comment by elesun2018** [comment]
finetune数据集是中文的，是unicode编码

IndexError: The shape of the mask [4, 1249] at index 0 does not match the shape of the indexed tensor [1, 1249, 4096] at index 0

**Comment by elesun2018** [comment]
我们本来就是prompt和label都是字符串
quention id=unikey=label这个是用于验证测试的？应该如何设置

**Comment by 1049451037** [comment]
> finetune数据集是中文的，是unicode编码
> 
> IndexError: The shape of the mask [4, 1249] at index 0 does not match the shape of the indexed tensor [1, 1249, 4096] at index 0

请提供完整的错误日志，或者至少提供一下是哪一行代码报的这个错误……

**Comment by elesun2018** [comment]
[2024-01-23 02:53:13,025] [INFO] [logging.py:96:log_dist] [Rank 0] step=10, skipped=0, lr=[5.000000000000001e-07, 5.000000000000001e-07], mom=[[0.9, 0.95], [0.9, 0.95]]
[2024-01-23 02:53:13,062] [INFO] [timer.py:260:stop] epoch=0/micro_step=10/global_step=10, RunningAvgSamplesPerSec=0.6679428030627035, CurrSamplesPerSec=0.6613724438818298, MemAllocated=38.75GB, MaxMemAllocated=43.77GB
Traceback (most recent call last):
  File "/home/sfz/examples/CogVLM/finetune_demo/finetune_cogvlm_demo.py", line 256, in <module>
    model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor), collate_fn=data_collator, forward_step_eval=forward_step_eval)
  File "/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/sat/training/deepspeed_training.py", line 150, in training_main
    iteration, skipped = train(model, optimizer,
  File "/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/sat/training/deepspeed_training.py", line 399, in train
    evaluate_and_print_results(
  File "/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/sat/training/deepspeed_training.py", line 597, in evaluate_and_print_results
    lm_loss, metrics = evaluate(data_iterator, model, eval_iters, args, timers, split, verbose, has_last, hooks=hooks)
  File "/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/sat/training/deepspeed_training.py", line 541, in evaluate
    lm_loss, metrics = forward_step(data_iterator, model, args, timers)
  File "/home/sfz/examples/CogVLM/finetune_demo/finetune_cogvlm_demo.py", line 186, in forward_step_eval
    outputs = chat(model, tokenizer, tokens, **data_b)[0][context_len:]
  File "/home/sfz/examples/CogVLM/finetune_demo/finetune_cogvlm_demo.py", line 123, in chat
    output = filling_sequence(
  File "/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/sat/generation/autoregressive_sampling.py", line 112, in filling_sequence
    logits, *output_per_layers = model(
  File "/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1829, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sfz/examples/CogVLM/utils/models/cogvlm_model.py", line 119, in forward
    return super().forward(input_ids=input_ids, vision_expert_mask=vision_expert_mask, image_embed_mask=image_embed_mask, **kwargs)
  File "/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/sat/model/base_model.py", line 137, in forward
    return self.transformer(*args, **kwargs)
  File "/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sfz/soft/miniconda3/envs/test12/lib/python3.10/site-packages/sat/model/transformer.py", line 545, in forward
    hidden_states = self.hooks['word_embedding_forward'](input_ids, output_cross_layer=output_cross_layer, **kw_args)
  File "/home/sfz/examples/CogVLM/utils/models/cogvlm_model.py", line 96, in word_embedding_forward
    word_embedding[image_embed_mask.bool()] = torch.cat([self.boi.repeat(len(image_emb), 1, 1), image_emb, self.eoi.repeat(len(image_emb), 1, 1)], dim=1).reshape(-1, image_emb.shape[-1])
IndexError: The shape of the mask [4, 1255] at index 0 does not match the shape of the indexed tensor [1, 1255, 4096] at index 0
sfz:5128:5206 [0] NCCL INFO [Service thread] Connection closed by localRank 0
sfz:5128:5128 [0] NCCL INFO comm 0x37661350 rank 0 nranks 1 cudaDev 0 busId 1000 - Abort COMPLETE
sfz:5128:5284 [0] NCCL INFO [Service thread] Connection closed by localRank 0
sfz:5128:5128 [0] NCCL INFO comm 0x28706bc0 rank 0 nranks 1 cudaDev 0 busId 1000 - Abort COMPLETE
[2024-01-23 02:53:14,602] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 5128
[2024-01-23 02:53:14,603] [ERROR] [launch.py:321:sigkill_handler] ['/home/sfz/soft/miniconda3/envs/test12/bin/python', '-u', 'finetune_demo/finetune_cogvlm_demo.py', '--local_rank=0', '--experiment-name', 'finetune-cogvlm', '--model-parallel-size', '1', '--mode', 'finetune', '--train-iters', '100', '--resume-dataloader', '--from_pretrained', 'cogvlm-base-490', '--max_length', '1288', '--lora_rank', '10', '--use_lora', '--local_tokenizer', '/home/sfz/models/vicuna-7b-v1.3', '--version', 'base', '--train-data', '/home/ssd1/data/cog_30W_15labels_0119/train', '--valid-data', '/home/ssd1/data/cog_30W_15labels_0119/valid', '--distributed-backend', 'nccl', '--lr-decay-style', 'cosine', '--warmup', '.02', '--checkpoint-activations', '--vit_checkpoint_activations', '--save-interval', '2000', '--eval-interval', '10', '--save', './checkpoints', '--eval-iters', '10', '--eval-batch-size', '4', '--split', '1.', '--deepspeed_config', 'finetune_demo/test_config_bf16.json', '--skip-init', '--seed', '2023'] exits with return code = 1

**Comment by elesun2018** [comment]
能否指点一下，谢谢

**Comment by denny3388** [comment]
也碰到了一樣的問題

**Comment by denny3388** [comment]
@elesun2018 我後來把參數裡的 --eval-batch-size 調成 1 之後就順利解決了，你可以去檢查看看你的 --eval-batch-size 是不是調成其他數字了。
我猜會出現 shape not match 的原因是，官方 code 現在只支援一次 inference 一張圖片配上一個文字，但若 --eval-batch-size > 1 的話，就會在 inference 時一次數入多張圖片和一個文字，就會造成錯誤。
