### ISSUE TITLE
RuntimeError: FIND was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by zihui-debug** [THUDM/CogVLM#409]
我在微调时遇到了下面的报错，看起来是环境配置的问题。
系统信息：
ubuntu 20.04.02
cuda 11.8 | torch 2.0.0+cu118 | cudnn 8.9.7
使用的是8张3090，检查了下cuda和cudnn可以使用，是其他地方有什么冲突吗？
![2b78e54c0d5c41f1f27b674e738a587](https://github.com/THUDM/CogVLM/assets/57470281/a85a3f95-2626-459e-afdb-ac6ed40ea813)
安装的包：
```
accelerate                0.27.2
aiohttp                   3.9.3
aiosignal                 1.3.1
altair                    5.2.0
annotated-types           0.6.0
anyio                     4.3.0
async-timeout             4.0.3
attrs                     23.2.0
blinker                   1.7.0
blis                      0.7.11
boto3                     1.34.59
botocore                  1.34.59
braceexpand               0.1.7
cachetools                5.3.3
catalogue                 2.0.10
certifi                   2024.2.2
charset-normalizer        3.3.2
click                     8.1.7
cloudpathlib              0.16.0
cmake                     3.28.3
confection                0.1.4
contourpy                 1.2.0
cpm-kernels               1.0.11
cycler                    0.12.1
cymem                     2.0.8
datasets                  2.18.0
deepspeed                 0.14.0
dill                      0.3.8
distro                    1.9.0
einops                    0.7.0
en-core-web-sm            3.7.1
exceptiongroup            1.2.0
fastapi                   0.110.0
filelock                  3.13.1
fonttools                 4.49.0
frozenlist                1.4.1
fsspec                    2024.2.0
gitdb                     4.0.11
GitPython                 3.1.42
h11                       0.14.0
hjson                     3.1.0
httpcore                  1.0.4
httpx                     0.27.0
huggingface-hub           0.21.4
idna                      3.6
Jinja2                    3.1.3
jmespath                  1.0.1
jsonschema                4.21.1
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
langcodes                 3.3.0
lit                       17.0.6
loguru                    0.7.2
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.8.3
mdurl                     0.1.2
mpmath                    1.3.0
multidict                 6.0.5
multiprocess              0.70.16
murmurhash                1.0.10
mypy-extensions           1.0.0
networkx                  3.2.1
ninja                     1.11.1.1
numpy                     1.26.4
nvidia-cublas-cu11        11.11.3.6
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu11    11.8.87
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu11    11.8.89
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu11  11.8.89
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu11         8.7.0.84
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu11         10.9.0.58
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu11        10.3.0.86
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu11      11.4.1.48
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu11      11.7.5.86
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu11          2.19.3
nvidia-nccl-cu12          2.19.3
nvidia-nvjitlink-cu12     12.4.99
nvidia-nvtx-cu11          11.8.86
nvidia-nvtx-cu12          12.1.105
openai                    1.13.3
packaging                 23.2
pandas                    2.2.1
pillow                    10.2.0
pip                       23.3.1
preshed                   3.0.9
protobuf                  4.25.3
psutil                    5.9.8
py-cpuinfo                9.0.0
pyarrow                   15.0.1
pyarrow-hotfix            0.6
pydantic                  2.6.3
pydantic_core             2.16.3
pydeck                    0.8.1b0
Pygments                  2.17.2
pynvml                    11.5.0
pyparsing                 3.1.2
pyre-extensions           0.0.23
python-dateutil           2.9.0.post0
pytz                      2024.1
PyYAML                    6.0.1
referencing               0.33.0
regex                     2023.12.25
requests                  2.31.0
rich                      13.7.1
rpds-py                   0.18.0
s3transfer                0.10.0
safetensors               0.4.2
seaborn                   0.13.2
sentencepiece             0.2.0
setuptools                68.2.2
six                       1.16.0
smart-open                6.4.0
smmap                     5.0.1
sniffio                   1.3.1
spacy                     3.7.4
spacy-legacy              3.0.12
spacy-loggers             1.0.5
srsly                     2.4.8
sse-starlette             2.0.0
starlette                 0.36.3
streamlit                 1.32.0
SwissArmyTransformer      0.4.11
sympy                     1.12
tenacity                  8.2.3
tensorboardX              2.6.2.2
thinc                     8.2.3
timm                      0.9.16
tokenizers                0.15.2
toml                      0.10.2
toolz                     0.12.1
torch                     2.0.0+cu118
torchaudio                2.0.1+cu118
torchvision               0.15.1+cu118
tornado                   6.4
tqdm                      4.66.2
transformers              4.38.2
triton                    2.0.0
typer                     0.9.0
typing_extensions         4.10.0
typing-inspect            0.9.0
tzdata                    2024.1
urllib3                   2.0.7
uvicorn                   0.28.0
wasabi                    1.1.2
watchdog                  4.0.0
weasel                    0.3.4
webdataset                0.2.86
wheel                     0.41.2
xformers                  0.0.18
xxhash                    3.4.1
yarl                      1.9.4
```

```
Traceback (most recent call last):
  File "finetune_cogvlm_demo.py", line 256, in <module>
    model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor), collate_fn=data_collator, forward_step_eval=forward_step_eval)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/training/deepspeed_training.py", line 150, in training_main
    iteration, skipped = train(model, optimizer,
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/training/deepspeed_training.py", line 349, in train
    lm_loss, skipped_iter, metrics = train_step(train_data_iterator,
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/training/deepspeed_training.py", line 429, in train_step
    forward_ret = forward_step(data_iterator, model, args, timers, **kwargs)
  File "finetune_cogvlm_demo.py", line 205, in forward_step
    logits = model(**data_b)[0]
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
Traceback (most recent call last):
    return forward_call(*args, **kwargs)
  File "finetune_cogvlm_demo.py", line 256, in <module>
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1852, in forward
    model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor), collate_fn=data_collator, forward_step_eval=forward_step_eval)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/training/deepspeed_training.py", line 150, in training_main
    iteration, skipped = train(model, optimizer,
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/training/deepspeed_training.py", line 349, in train
    lm_loss, skipped_iter, metrics = train_step(train_data_iterator,
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/training/deepspeed_training.py", line 429, in train_step
    loss = self.module(*inputs, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    forward_ret = forward_step(data_iterator, model, args, timers, **kwargs)
  File "finetune_cogvlm_demo.py", line 205, in forward_step
    logits = model(**data_b)[0]
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/zhengsr/CogVLM/utils/models/cogvlm_model.py", line 119, in forward
    return super().forward(input_ids=input_ids, vision_expert_mask=vision_expert_mask, image_embed_mask=image_embed_mask, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/model/base_model.py", line 137, in forward
        return forward_call(*args, **kwargs)return self.transformer(*args, **kwargs)

  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1852, in forward
    return self._call_impl(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    loss = self.module(*inputs, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/model/transformer.py", line 545, in forward
    return self._call_impl(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    hidden_states = self.hooks['word_embedding_forward'](input_ids, output_cross_layer=output_cross_layer, **kw_args)
  File "/data/zhengsr/CogVLM/utils/models/cogvlm_model.py", line 91, in word_embedding_forward
    image_emb = self.vit_model(**vision_inputs)[0]
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return forward_call(*args, **kwargs)
  File "/data/zhengsr/CogVLM/utils/models/cogvlm_model.py", line 119, in forward
    return super().forward(input_ids=input_ids, vision_expert_mask=vision_expert_mask, image_embed_mask=image_embed_mask, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/model/base_model.py", line 137, in forward
    return self._call_impl(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return self.transformer(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
Traceback (most recent call last):
  File "finetune_cogvlm_demo.py", line 256, in <module>
    return forward_call(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/model/base_model.py", line 137, in forward
    return self._call_impl(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return self.transformer(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor), collate_fn=data_collator, forward_step_eval=forward_step_eval)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/training/deepspeed_training.py", line 150, in training_main
    iteration, skipped = train(model, optimizer,
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/training/deepspeed_training.py", line 349, in train
    lm_loss, skipped_iter, metrics = train_step(train_data_iterator,
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/training/deepspeed_training.py", line 429, in train_step
    return forward_call(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/model/transformer.py", line 545, in forward
Traceback (most recent call last):
    return self._call_impl(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
  File "finetune_cogvlm_demo.py", line 256, in <module>
    forward_ret = forward_step(data_iterator, model, args, timers, **kwargs)
  File "finetune_cogvlm_demo.py", line 205, in forward_step
    hidden_states = self.hooks['word_embedding_forward'](input_ids, output_cross_layer=output_cross_layer, **kw_args)
      File "/data/zhengsr/CogVLM/utils/models/cogvlm_model.py", line 91, in word_embedding_forward
logits = model(**data_b)[0]
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
        model = training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=partial(create_dataset_function, image_processor, text_processor), collate_fn=data_collator, forward_step_eval=forward_step_eval)image_emb = self.vit_model(**vision_inputs)[0]

  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/training/deepspeed_training.py", line 150, in training_main
        return forward_call(*args, **kwargs)iteration, skipped = train(model, optimizer,

  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/model/transformer.py", line 545, in forward
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/training/deepspeed_training.py", line 349, in train
    lm_loss, skipped_iter, metrics = train_step(train_data_iterator,
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/training/deepspeed_training.py", line 429, in train_step
    hidden_states = self.hooks['word_embedding_forward'](input_ids, output_cross_layer=output_cross_layer, **kw_args)
      File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/model/official/vit_model.py", line 54, in word_embedding_forward
return self._call_impl(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    embeddings = self.proj(images)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    forward_ret = forward_step(data_iterator, model, args, timers, **kwargs)
  File "finetune_cogvlm_demo.py", line 205, in forward_step
    logits = model(**data_b)[0]
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    return forward_call(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/model/base_model.py", line 137, in forward
        return self._call_impl(*args, **kwargs)ret_val = func(*args, **kwargs)

  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1852, in forward
    return self.transformer(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._call_impl(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    loss = self.module(*inputs, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    ret_val = func(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1852, in forward
    return F.conv2d(input, weight, bias, self.stride,
    return forward_call(*args, **kwargs)
RuntimeError  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/model/transformer.py", line 545, in forward
: FIND was unable to find an engine to execute this computation
    return self._call_impl(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    hidden_states = self.hooks['word_embedding_forward'](input_ids, output_cross_layer=output_cross_layer, **kw_args)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/model/official/vit_model.py", line 54, in word_embedding_forward
    embeddings = self.proj(images)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    loss = self.module(*inputs, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return forward_call(*args, **kwargs)
  File "/data/zhengsr/CogVLM/utils/models/cogvlm_model.py", line 119, in forward
    return super().forward(input_ids=input_ids, vision_expert_mask=vision_expert_mask, image_embed_mask=image_embed_mask, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/model/base_model.py", line 137, in forward
    return self._call_impl(*args, **kwargs)
      File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
return self.transformer(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._call_impl(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/zhengsr/CogVLM/utils/models/cogvlm_model.py", line 119, in forward
    return super().forward(input_ids=input_ids, vision_expert_mask=vision_expert_mask, image_embed_mask=image_embed_mask, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/model/base_model.py", line 137, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return self.transformer(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: FIND was unable to find an engine to execute this computation
    return forward_call(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/model/transformer.py", line 545, in forward
    hidden_states = self.hooks['word_embedding_forward'](input_ids, output_cross_layer=output_cross_layer, **kw_args)
  File "/data/zhengsr/CogVLM/utils/models/cogvlm_model.py", line 91, in word_embedding_forward
    return self._call_impl(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    image_emb = self.vit_model(**vision_inputs)[0]
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/model/transformer.py", line 545, in forward
    return self._call_impl(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    hidden_states = self.hooks['word_embedding_forward'](input_ids, output_cross_layer=output_cross_layer, **kw_args)
  File "/data/zhengsr/CogVLM/utils/models/cogvlm_model.py", line 91, in word_embedding_forward
    image_emb = self.vit_model(**vision_inputs)[0]
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/model/base_model.py", line 137, in forward
    return self.transformer(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/model/base_model.py", line 137, in forward
    return self.transformer(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/model/transformer.py", line 545, in forward
    hidden_states = self.hooks['word_embedding_forward'](input_ids, output_cross_layer=output_cross_layer, **kw_args)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/model/official/vit_model.py", line 54, in word_embedding_forward
    return self._call_impl(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    embeddings = self.proj(images)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/model/transformer.py", line 545, in forward
    return self._call_impl(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    hidden_states = self.hooks['word_embedding_forward'](input_ids, output_cross_layer=output_cross_layer, **kw_args)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/sat/model/official/vit_model.py", line 54, in word_embedding_forward
    embeddings = self.proj(images)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return self._call_impl(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: FIND was unable to find an engine to execute this computation
    return forward_call(*args, **kwargs)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/zhengshurong/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: FIND was unable to find an engine to execute this computation
```

**Comment by zihui-debug** [comment]
已解决，conda定位到.local下的包了

**Comment by liuq0123** [comment]
你好，我也遇到这个问题了，请问您怎么解决的
