### ISSUE TITLE
KeyError: 'cogvlm-chat'

### ISSUE THREAD

**Issue by AmmaraRazzaq** [THUDM/CogVLM#426]
### System Info / 系統信息

Ubuntu 

### Who can help? / 谁可以帮助到您？

@zRzRzRzRzRzRzR 
@zr

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

python cli_demo_sat.py --from_pretrained cogvlm-chat --version chat_old --bf16 --stream_chat

[2024-03-24 03:53:51,492] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "cli_demo_sat.py", line 161, in <module>
    main()
  File "cli_demo_sat.py", line 36, in main
    model, model_args = AutoModel.from_pretrained(
  File "/home/ammara/miniconda3/envs/cogvlm/lib/python3.8/site-packages/sat/model/base_model.py", line 337, in from_pretrained
    return cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=build_only, overwrite_args=overwrite_args, **kwargs)
  File "/home/ammara/miniconda3/envs/cogvlm/lib/python3.8/site-packages/sat/model/base_model.py", line 312, in from_pretrained_base
    model_path = auto_create(name, path=home_path, url=url)
  File "/home/ammara/miniconda3/envs/cogvlm/lib/python3.8/site-packages/sat/resources/download.py", line 53, in auto_create
    url = MODEL_URLS[name]
KeyError: 'cogvlm-chat'

### Expected behavior / 期待表现

The model should run without error

**Comment by zRzRzRzRzRzRzR** [comment]
换成模型绝对路径
