### ISSUE TITLE
类型问题

### ISSUE THREAD

**Issue by Shawnzheng011019** [THUDM/CogVLM#506]
### System Info / 系統信息

SwissArmyTransformer>=0.4.9
transformers>=4.36.2
xformers>=0.0.22
torch>=2.1.0
torchvision>=0.16.2
spacy>=3.6.0
pillow>=10.2.0
deepspeed>=0.13.1
seaborn>=0.13.2
loguru~=0.7.2
streamlit>=1.31.0
timm>=0.9.12
accelerate>=0.26.1
pydantic>=2.6.0

# for openai demo
openai>=1.16.0
sse-starlette>=1.8.2
fastapi>=0.110.1
httpx>=0.27.0
uvicorn>=0.29.0
jsonlines>=4.0.0

### Who can help? / 谁可以帮助到您？

@zRzRzRzRzRzRzR 请问以下报错如何解决，是否是读取图片路径时的问题：
image path >>>>> /workspace/CogVLM-chat/test.png
Human:图片里面包含什么内容
/root/miniconda3/envs/cogvlm/lib/python3.8/site-packages/bitsandbytes/nn/modules.py:426: UserWarning: Input type into Linear4bit is torch.float16, but bnb_4bit_compute_dtype=torch.float32 (default). This will lead to slow inference or training speed.
  warnings.warn(
Traceback (most recent call last):
  File "cli_demo_hf.py", line 98, in <module>
    outputs = model.generate(**inputs, **gen_kwargs)
  File "/root/miniconda3/envs/cogvlm/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/cogvlm/lib/python3.8/site-packages/transformers/generation/utils.py", line 1914, in generate
    result = self._sample(
  File "/root/miniconda3/envs/cogvlm/lib/python3.8/site-packages/transformers/generation/utils.py", line 2651, in _sample
    outputs = self(
  File "/root/miniconda3/envs/cogvlm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/cogvlm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/cogvlm/lib/python3.8/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/cogvlm-chat-hf/modeling_cogvlm.py", line 660, in forward
    outputs = self.model(
  File "/root/miniconda3/envs/cogvlm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/cogvlm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/cogvlm/lib/python3.8/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/cogvlm-chat-hf/modeling_cogvlm.py", line 442, in forward
    return self.llm_forward(
  File "/root/.cache/huggingface/modules/transformers_modules/cogvlm-chat-hf/modeling_cogvlm.py", line 491, in llm_forward
    past_key_values_length = past_key_values[0][0].shape[2]
AttributeError: 'str' object has no attribute 'shape'

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

python cli_demo_hf.py --from_pretrained /workspace/CogVLM-chat/models/cogvlm-chat-hf --fp16 --quant 4

### Expected behavior / 期待表现

在openaiapi或终端调用时能够成功读取图片

**Comment by allanraventos** [comment]
Getting the same error with agent

**Comment by MachineDora** [comment]
transformers==4.31.2，transfomers的版本太高了，改成4.31.2。
