### ISSUE TITLE
KeyError: 'cogvlm-chat'

### ISSUE THREAD

**Issue by nulllt** [THUDM/CogVLM#524]
### System Info / 系統信息

python 3.8，cuda11.8

### Who can help? / 谁可以帮助到您？

@zr

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

python cli_demo_sat.py --from_pretrained cogvlm-chat --version chat_old --bf16  --stream_chat

[2024-09-05 15:30:54,430] [WARNING] Failed to load bitsandbytes:No module named 'bitsandbytes'
Traceback (most recent call last):
  File "/home/lt/2024/llm/CogVLM/basic_demo/cli_demo_sat.py", line 161, in <module>
    main()
  File "/home/lt/2024/llm/CogVLM/basic_demo/cli_demo_sat.py", line 36, in main
    model, model_args = AutoModel.from_pretrained(
  File "/home/lt/miniconda3/lib/python3.10/site-packages/sat/model/base_model.py", line 342, in from_pretrained
    return cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=build_only, overwrite_args=overwrite_args, **kwargs)
  File "/home/lt/miniconda3/lib/python3.10/site-packages/sat/model/base_model.py", line 317, in from_pretrained_base
    model_path = auto_create(name, path=home_path, url=url)
  File "/home/lt/miniconda3/lib/python3.10/site-packages/sat/resources/download.py", line 53, in auto_create
    url = MODEL_URLS[name]
KeyError: 'cogvlm-chat'

### Expected behavior / 期待表现

The model will be downloaded.

**Comment by IceIce1ce** [comment]
+1
