### ISSUE TITLE
 cannot import name 'rotate_half' from 'sat.model.official.llama_model' 

### ISSUE THREAD

**Issue by kkkwjr** [THUDM/CogVLM#535]
python cli_demo_sat.py --from_pretrained cogagent-chat --version chat --bf16  --stream_chat
[2024-11-28 05:54:25,880] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/workspace/kkkjr/Item/CogVLM/basic_demo/cli_demo_sat.py", line 12, in <module>
    from utils.utils import chat, llama2_tokenizer, llama2_text_processor_inference, get_image_processor
  File "/workspace/kkkjr/Item/CogVLM/utils/utils/__init__.py", line 2, in <module>
    from .language import llama2_tokenizer, llama2_text_processor, llama2_text_processor_inference
  File "/workspace/kkkjr/Item/CogVLM/utils/utils/language.py", line 1, in <module>
    from sat.model.official.llama_model import LLaMAModel, rotate_half
ImportError: cannot import name 'rotate_half' from 'sat.model.official.llama_model' (/home/wpg/anaconda3/envs/CogAgent/lib/python3.9/site-packages/sat/model/official/llama_model.py)

为啥会出现引入不了 'rotate_half'的情况呢

**Comment by xjywhu** [comment]
也遇到了一样的问题，请问您解决了吗

**Comment by Adam-ly-captain** [comment]
pip install SwissArmyTransformer==0.4.9
解决rotate_half问题

**Comment by rehan243** [comment]
Are you using the latest version of sat? I ran into a similar issue with imports from sat.model.official.llama_model and it turned out I was on an older version that didn't have the rotate_half function. I've seen this kind of thing before when the sat library gets updated but the CogVLM code hasn't been synced up yet. The error message is pointing to /home/wpg/anaconda3/envs/CogAgent/lib/python3.9/site-packages/sat/model/official/llama_model.py, so I'd check that file to see if rotate_half is actually defined there. If not, it's likely a version mismatch. I've had to manually check library versions like this before, took me a few tries to get it right. What's your sat version, btw?
