### ISSUE TITLE
ncclUnhandledCudaError: Call to CUDA function failed.

### ISSUE THREAD

**Issue by zslittlehelper** [THUDM/CogVLM#56]
Environment: WSL2, Ubuntu 22.04, running in a conda environment with python 3.10.
Cuda12.1 is installed and working with other tasks like ExLllamaV2.
Hardware wise I have one 4090 and a 3090Ti.

After installation I attempted to run this command: torchrun --standalone --nnodes=1 --nproc-per-node=2 cli_demo.py --from_pretrained cogvlm-chat --version chat --english --bf16

The model loaded, but then threw this error:

> (cogvlm) user@DESKTOP-User:~/CogVLM$ torchrun --standalone --nnodes=1 --nproc-per-node=2 cli_demo.py --from_pretrained cogvlm-chat --version chat --english --bf16
[2023-10-26 22:47:16,010] torch.distributed.run: [WARNING] master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
[2023-10-26 22:47:16,010] torch.distributed.run: [WARNING]
[2023-10-26 22:47:16,010] torch.distributed.run: [WARNING] *****************************************
[2023-10-26 22:47:16,010] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
[2023-10-26 22:47:16,010] torch.distributed.run: [WARNING] *****************************************
[2023-10-26 22:47:18,276] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-26 22:47:18,299] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-26 22:47:18,781] [WARNING] Failed to load bitsandbytes:No module named 'bitsandbytes'
[2023-10-26 22:47:18,781] [WARNING] Failed to load bitsandbytes:No module named 'bitsandbytes'
[2023-10-26 22:47:18,925] [INFO] building CogVLMModel model ...
[2023-10-26 22:47:18,925] [INFO] building CogVLMModel model ...
[2023-10-26 22:47:20,543] [INFO] [RANK 0] > initializing model parallel with size 2
[2023-10-26 22:47:20,543] [INFO] [RANK 0] You are using model-only mode.
For torch.distributed users or loading model parallel models, set environment variables RANK, WORLD_SIZE and LOCAL_RANK.
[2023-10-26 22:47:26,335] [INFO] [RANK 1]  > number of parameters on model parallel rank 1: 8893252992
[2023-10-26 22:47:27,171] [INFO] [RANK 0]  > number of parameters on model parallel rank 0: 8893252992
[2023-10-26 22:47:30,484] [INFO] [RANK 0] > initializing model parallel with size 1
[2023-10-26 22:47:30,485] [INFO] [RANK 0] building CogVLMModel model ...
[2023-10-26 22:47:35,073] [INFO] [RANK 0]  > number of parameters on model parallel rank 0: 17639685376
[2023-10-26 22:47:40,102] [INFO] [RANK 0] global rank 0 is loading checkpoint /home/user/.sat_models/cogvlm-chat/1/mp_rank_00_model_states.pt
[2023-10-26 22:48:15,001] [INFO] [RANK 0] > successfully loaded /home/user/.sat_models/cogvlm-chat/1/mp_rank_00_model_states.pt
Traceback (most recent call last):
  File "/home/user/CogVLM/cli_demo.py", line 154, in <module>
    main()
  File "/home/user/CogVLM/cli_demo.py", line 34, in main
    model, model_args = CogVLMModel.from_pretrained(
  File "/home/user/miniconda3/envs/cogvlm/lib/python3.10/site-packages/sat/model/base_model.py", line 232, in from_pretrained
    torch.distributed.barrier()
  File "/home/user/miniconda3/envs/cogvlm/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/user/miniconda3/envs/cogvlm/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3696, in barrier
    work = default_pg.barrier(opts=opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1331, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.18.1
ncclUnhandledCudaError: Call to CUDA function failed.
Last error:
Cuda failure 'invalid argument'
Traceback (most recent call last):
  File "/home/user/CogVLM/cli_demo.py", line 154, in <module>
    main()
  File "/home/user/CogVLM/cli_demo.py", line 34, in main
    model, model_args = CogVLMModel.from_pretrained(
  File "/home/user/miniconda3/envs/cogvlm/lib/python3.10/site-packages/sat/model/base_model.py", line 232, in from_pretrained
    torch.distributed.barrier()
  File "/home/user/miniconda3/envs/cogvlm/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/user/miniconda3/envs/cogvlm/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3696, in barrier
    work = default_pg.barrier(opts=opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1331, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.18.1
ncclUnhandledCudaError: Call to CUDA function failed.
Last error:
Cuda failure 'invalid argument'
[2023-10-26 22:48:26,410] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 947) of binary: /home/user/miniconda3/envs/cogvlm/bin/python
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/cogvlm/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/user/miniconda3/envs/cogvlm/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/user/miniconda3/envs/cogvlm/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/user/miniconda3/envs/cogvlm/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/user/miniconda3/envs/cogvlm/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/user/miniconda3/envs/cogvlm/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
cli_demo.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-10-26_22:48:26
  host      : DESKTOP-User.
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 948)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-26_22:48:26
  host      : DESKTOP-User.
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 947)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by Mingzefei** [comment]
I get the same issue with the following environment and hardware.


Environment: WSL2, Ubuntu 20.04, running in a conda environment with python 3.11 and cuda 12.1
Hardware: two 4090 GPU

**Comment by 1049451037** [comment]
It's the problem of your environment, which I cannot control.

Try:

1. Update your cuda driver.
2. Install the right version of torch, corresponding to your cuda version (You can print `torch.version.cuda` to see you torch cuda version)

**Comment by 1049451037** [comment]
Seems like a problem of WSL2 running multi-gpu code. I have no idea of dealing with this.

ref:

* https://discuss.pytorch.org/t/how-can-i-use-multiple-gpus-on-wsl2/94002/4
* https://github.com/microsoft/WSL/issues/10269

**Comment by zslittlehelper** [comment]
> Seems like a problem of WSL2 running multi-gpu code. I have no idea of dealing with this.
> 
> ref:
> 
>     * https://discuss.pytorch.org/t/how-can-i-use-multiple-gpus-on-wsl2/94002/4
> 
>     * [CUDA Initialization Issue and Proposed Workaround with PyTorch in wsl2 microsoft/WSL#10269](https://github.com/microsoft/WSL/issues/10269)

Multi-gpu works well for deepspeed training with axolotl, and with exllama2. In the case of cogvlm, the model *is* loaded, it's just that it calls some cuda function in a way others do not.

So it's less of a general issue, and instead an implementation problem within cogvlm.

**Comment by 1049451037** [comment]
Maybe you didn't use point-to-point communication when you train with deepspeed. You just need all_reduce.

However, if you use model parallel in SAT, you need to call something like `torch.distributed.recv` and `torch.distributed.send`. Maybe WSL2 doesn't support those operations?

**Comment by 1049451037** [comment]
https://huggingface.co/THUDM/cogvlm-chat-hf/discussions/2#655ccd16605e1e91fb226cd8

Here is an example of running in WSL2 with huggingface accelerate! I will try adding the feature in sat soon :)
