### ISSUE TITLE
CUDA error: the launch timed out and was terminated

### ISSUE THREAD

**Issue by hxgqh** [THUDM/CogVLM#67]
command: 

```bash
torchrun --standalone --nnodes=1 --nproc-per-node=2 cli_demo.py --from_pretrained cogvlm-chat --version chat --english --bf16
```

error log:

```log
Welcome to CogVLM-CLI. Enter an image URL or local file path to load an image. Continue inputting text to engage in a conversation. Type "clear" to start over, or "stop" to end the program.
Please enter the image path or URL (press Enter for plain text conversation): [E ProcessGroupNCCL.cpp:915] [Rank 1] NCCL watchdog thread terminated with exception: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:44 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7feb7e992617 in /data/docker/thudm/CogVLM/venv/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7feb7e94d98d in /data/docker/thudm/CogVLM/venv/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7feb8a55e9f8 in /data/docker/thudm/CogVLM/venv/lib/python3.11/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x80 (0x7feb09f00af0 in /data/docker/thudm/CogVLM/venv/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0x58 (0x7feb09f04918 in /data/docker/thudm/CogVLM/venv/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::workCleanupLoop() + 0x24b (0x7feb09f1b15b in /data/docker/thudm/CogVLM/venv/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x78 (0x7feb09f1b468 in /data/docker/thudm/CogVLM/venv/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0xdbbf4 (0x7feb4eadbbf4 in /root/miniconda3/bin/../lib/libstdc++.so.6)
frame #8: <unknown function> + 0x94ac3 (0x7feb8b494ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0x126a40 (0x7feb8b526a40 in /lib/x86_64-linux-gnu/libc.so.6)

[2023-10-30 17:20:01,249] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 1806903 closing signal SIGTERM
[2023-10-30 17:20:04,350] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -6) local_rank: 1 (pid: 1806904) of binary: /data/docker/thudm/CogVLM/venv/bin/python3
Traceback (most recent call last):
  File "/data/docker/thudm/CogVLM/venv/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/docker/thudm/CogVLM/venv/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/data/docker/thudm/CogVLM/venv/lib/python3.11/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/data/docker/thudm/CogVLM/venv/lib/python3.11/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/data/docker/thudm/CogVLM/venv/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/docker/thudm/CogVLM/venv/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
========================================================
cli_demo.py FAILED
--------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
--------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-30_17:20:01
  host      : userroot-Super-Server
  rank      : 1 (local_rank: 1)
  exitcode  : -6 (pid: 1806904)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 1806904
```

**Comment by tkone2018** [comment]
@hxgqh 请问你解决了吗

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新代码并尝试多卡启动试试
