### ISSUE TITLE
Please make the code backward compatible with lower versions of PyTorch==2.0.1

### ISSUE THREAD

**Issue by ZetangForward** [THUDM/CogVLM#71]
Hi, the NVIDIA driver on my machine only supports PyTorch==2.0.1.
However, the code asks for the PyTorch==2.1.0 version. 
When I run the code, I meet the following error:

```
Traceback (most recent call last):
  File "/workspace/zecheng/SUWA/caption_gen/CogVLM/cogvlm_inference.py", line 100, in <module>
[2023-11-01 18:23:08,805] [WARNING] Failed to load bitsandbytes:No module named 'bitsandbytes'
    main()
  File "/workspace/zecheng/SUWA/caption_gen/CogVLM/cogvlm_inference.py", line 39, in main
    model, model_args = CogVLMModel.from_pretrained(
  File "/home/v-zetang/.conda/envs/llava/lib/python3.10/site-packages/sat/model/base_model.py", line 219, in from_pretrained
    model, model_args = cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=True, overwrite_args=overwrite_args, **kwargs)
  File "/home/v-zetang/.conda/envs/llava/lib/python3.10/site-packages/sat/model/base_model.py", line 201, in from_pretrained_base
    model_path = auto_create(name, path=home_path, url=url)
  File "/home/v-zetang/.conda/envs/llava/lib/python3.10/site-packages/sat/resources/download.py", line 50, in auto_create
    lock = FileLock(model_path + '.lock', mode=0o777)
TypeError: BaseFileLock.__init__() got an unexpected keyword argument 'mode'
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.0+cu121 with CUDA 1201 (you have 2.0.1)
    Python  3.10.13 (you have 3.10.13)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
[2023-11-01 18:23:08,819] [WARNING] Failed to load bitsandbytes:No module named 'bitsandbytes'
[2023-11-01 18:23:08,859] [WARNING] Failed to load bitsandbytes:No module named 'bitsandbytes'
[2023-11-01 18:23:08,866] [WARNING] Failed to load bitsandbytes:No module named 'bitsandbytes'
Exception ignored in: <function BaseFileLock.__del__ at 0x7f16225d13f0>
Traceback (most recent call last):
  File "/home/v-zetang/.conda/envs/llava/lib/python3.10/site-packages/filelock/_api.py", line 240, in __del__
    self.release(force=True)
  File "/home/v-zetang/.conda/envs/llava/lib/python3.10/site-packages/filelock/_api.py", line 201, in release
    with self._thread_lock:
AttributeError: 'UnixFileLock' object has no attribute '_thread_lock'

```

Can you make this code backward compatible with lower versions of PyTorch==2.0.1 ? Thank you.

**Comment by 1049451037** [comment]
It's not a PyTorch error. Just upgrade the filelock.

```
pip install -U filelock
```

**Comment by ZetangForward** [comment]
> It's not a PyTorch error. Just upgrade the filelock.
> 
> ```
> pip install -U filelock
> ```

Hi, actually, after I run the command ``pip install -r requirements.txt`` and use the code, I face the following error

```
[2023-11-02 03:10:02,991] torch.distributed.run: [WARNING] *****************************************
[2023-11-02 03:10:02,991] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2023-11-02 03:10:02,991] torch.distributed.run: [WARNING] *****************************************
/home/v-zetang/.conda/envs/cogvlm/lib/python3.10/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
```
and 

```
[2023-11-02 03:10:04,792] [INFO] DeepSpeed/CUDA is not installed, fallback to Pytorch checkpointing.
/home/v-zetang/.conda/envs/cogvlm/lib/python3.10/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
```

**Comment by 1049451037** [comment]
As you can see in your reported error:

```
UserWarning: CUDA initialization: The NVIDIA driver on your system is too old
```

It is the error that we cannot control. You should update your cuda driver.
