### ISSUE TITLE
interrupt when download the sat model

### ISSUE THREAD

**Issue by CarolXh** [THUDM/CogVLM#78]
while running the web_demo.py, it automatically download the sat model. But I meet thie problem as follows.

Failed to download or check, if you already had the zip file, please unzip it manually as /home/testenv/.sat_models/cogvlm-chat!
Traceback (most recent call last):
  File "/home/testenv/miniconda3/envs/llm/lib/python3.10/site-packages/urllib3/response.py", line 710, in _error_catcher
    yield
  File "/home/testenv/miniconda3/envs/llm/lib/python3.10/site-packages/urllib3/response.py", line 835, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(6885376 bytes read, 1503232 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/testenv/miniconda3/envs/llm/lib/python3.10/site-packages/botocore/response.py", line 99, in read
    chunk = self._raw_stream.read(amt)
  File "/home/testenv/miniconda3/envs/llm/lib/python3.10/site-packages/urllib3/response.py", line 879, in read
    data = self._raw_read(amt)
  File "/home/testenv/miniconda3/envs/llm/lib/python3.10/site-packages/urllib3/response.py", line 813, in _raw_read
    with self._error_catcher():
  File "/home/testenv/miniconda3/envs/llm/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/testenv/miniconda3/envs/llm/lib/python3.10/site-packages/urllib3/response.py", line 727, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(6885376 bytes read, 1503232 more expected)', IncompleteRead(6885376 bytes read, 1503232 more expected))

Is this because my cache is too small or other reasons? I am wondering where can I download the zip file directly. In the model file, I only find the urls: 
MODEL_URLS["cogvlm-chat"] = "r2://cogvlm-chat.zip"

**Comment by Baxkiller** [comment]
Hi, I meet the same question. Have you solved this problem yet?
