### ISSUE TITLE
Error running web_demo.py AttributeError: 'Chatbot' object has no attribute 'style'. Did you mean: 'scale'?

### ISSUE THREAD

**Issue by lxe** [THUDM/CogVLM#82]
Getting this error when running `web_demo.py` like this:

```
torchrun --standalone --nnodes=1 --nproc-per-node=2 web_demo.py --from_pretrained cogvlm-chat --version chat --english --bf16
```

```
Traceback (most recent call last):
  File "/home/lxe/CogVLM/web_demo.py", line 222, in <module>
    main(args)
  File "/home/lxe/CogVLM/web_demo.py", line 178, in main
    result_text = gr.components.Chatbot(label='Multi-round conversation History', value=[("", "Hi, What do you want to know about this image?")]).style(height=550)
AttributeError: 'Chatbot' object has no attribute 'style'. Did you mean: 'scale'?
```

Other info:

```
uname -iosrv
Linux 6.5.0-10-generic #10-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct 13 13:49:38 UTC 2023 x86_64 GNU/Linux
```

```
Package                   Version
------------------------- ------------
aiofiles                  23.2.1
aiohttp                   3.8.6
aiosignal                 1.3.1
altair                    5.1.2
analytics-python          1.4.post1
annotated-types           0.6.0
anyio                     3.7.1
async-timeout             4.0.3
attrs                     23.1.0
backoff                   1.10.0
bcrypt                    4.0.1
bitsandbytes              0.41.2.post2
blis                      0.7.11
boto3                     1.28.82
botocore                  1.31.82
braceexpand               0.1.7
catalogue                 2.0.10
certifi                   2023.7.22
cffi                      1.16.0
charset-normalizer        3.3.2
click                     8.1.7
cloudpathlib              0.16.0
colorama                  0.4.6
confection                0.1.3
contourpy                 1.2.0
cpm-kernels               1.0.11
cryptography              41.0.5
cycler                    0.12.1
cymem                     2.0.8
datasets                  2.14.6
deepspeed                 0.12.2
dill                      0.3.7
einops                    0.7.0
en-core-web-sm            3.7.0
exceptiongroup            1.1.3
fastapi                   0.104.1
ffmpeg-python             0.2.0
ffmpy                     0.3.1
filelock                  3.13.1
fonttools                 4.44.0
frozenlist                1.4.0
fsspec                    2023.10.0
gradio                    4.0.0
gradio_client             0.7.0
h11                       0.14.0
hjson                     3.1.0
httpcore                  1.0.1
httpx                     0.25.1
huggingface-hub           0.17.3
idna                      3.4
importlib-resources       6.1.1
Jinja2                    3.1.2
jmespath                  1.0.1
jsonschema                4.19.2
jsonschema-specifications 2023.7.1
kiwisolver                1.4.5
langcodes                 3.3.0
linkify-it-py             2.0.2
markdown-it-py            3.0.0
MarkupSafe                2.1.3
matplotlib                3.8.1
mdit-py-plugins           0.4.0
mdurl                     0.1.2
monotonic                 1.6
mpmath                    1.3.0
multidict                 6.0.4
multiprocess              0.70.15
murmurhash                1.0.10
networkx                  3.2.1
ninja                     1.11.1.1
numpy                     1.26.1
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu12          2.18.1
nvidia-nvjitlink-cu12     12.3.52
nvidia-nvtx-cu12          12.1.105
orjson                    3.9.10
packaging                 23.2
pandas                    2.1.2
paramiko                  3.3.1
Pillow                    10.1.0
pip                       23.3
preshed                   3.0.9
protobuf                  4.25.0
psutil                    5.9.6
py-cpuinfo                9.0.0
pyarrow                   14.0.1
pycparser                 2.21
pycryptodome              3.19.0
pydantic                  2.4.2
pydantic_core             2.10.1
pydub                     0.25.1
Pygments                  2.16.1
PyNaCl                    1.5.0
pynvml                    11.5.0
pyparsing                 3.1.1
python-dateutil           2.8.2
python-multipart          0.0.6
pytz                      2023.3.post1
PyYAML                    6.0.1
referencing               0.30.2
regex                     2023.10.3
requests                  2.31.0
rich                      13.6.0
rpds-py                   0.12.0
s3transfer                0.7.0
safetensors               0.4.0
scipy                     1.11.3
seaborn                   0.13.0
semantic-version          2.10.0
sentencepiece             0.1.99
setuptools                68.0.0
shellingham               1.5.4
six                       1.16.0
smart-open                6.4.0
sniffio                   1.3.0
spacy                     3.7.2
spacy-legacy              3.0.12
spacy-loggers             1.0.5
srsly                     2.4.8
starlette                 0.27.0
SwissArmyTransformer      0.4.8
sympy                     1.12
tensorboardX              2.6.2.2
thinc                     8.2.1
tokenizers                0.14.1
tomlkit                   0.12.0
toolz                     0.12.0
torch                     2.1.0
torchaudio                2.1.0
torchvision               0.16.0
tqdm                      4.66.1
transformers              4.35.0
triton                    2.1.0
typer                     0.9.0
typing_extensions         4.8.0
tzdata                    2023.3
uc-micro-py               1.0.2
urllib3                   2.0.7
uvicorn                   0.24.0.post1
wasabi                    1.1.2
weasel                    0.3.4
webdataset                0.2.74
websockets                11.0.3
wheel                     0.41.2
xformers                  0.0.22.post7
xxhash                    3.4.1
yarl                      1.9.2
```

**Comment by 1049451037** [comment]
You can downgrade `gradio` from 4.x to 3.x.
