### ISSUE TITLE
Request for CPU option inference

### ISSUE THREAD

**Issue by rusuanjun007** [THUDM/CogVLM#85]
Hello,

Is there any plan to add a "cpu" option for model inference?

**Comment by 1049451037** [comment]
Yes, just replace this line with device='cpu'

https://github.com/THUDM/CogVLM/blob/3c254565408e180207de8a0b69f20473ecd5c157/cli_demo.py#L45

**Comment by akshat-khare** [comment]
Hi, Tried above on a publicly available colab and it threw following error:
```
[2023-11-15 20:57:02,465] [INFO] DeepSpeed/CUDA is not installed, fallback to Pytorch checkpointing.
[2023-11-15 20:57:04,790] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.0+cu121 with CUDA 1201 (you have 2.1.0+cu118)
    Python  3.10.13 (you have 3.10.12)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
[2023-11-15 20:57:08,446] [WARNING] Failed to load bitsandbytes:No module named 'bitsandbytes'
Downloading models r2://cogvlm-base-224.zip into /root/.sat_models ...
/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'c8a00746a80e06c4632028e37de24d6e.r2.cloudflarestorage.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++100.0% 28.0 GB / 28.0 GB     
Unzipping /root/.sat_models/cogvlm-base-224.zip...
[2023-11-15 21:09:28,958] [INFO] building CogVLMModel model ...
Traceback (most recent call last):
  File "/content/CogVLM/cli_demo.py", line 154, in <module>
    main()
  File "/content/CogVLM/cli_demo.py", line 34, in main
    model, model_args = CogVLMModel.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/sat/model/base_model.py", line 215, in from_pretrained
    return cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=build_only, overwrite_args=overwrite_args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sat/model/base_model.py", line 207, in from_pretrained_base
    model = get_model(args, cls, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sat/model/base_model.py", line 379, in get_model
    model = model_cls(args, params_dtype=params_dtype, **kwargs)
  File "/content/CogVLM/models/cogvlm_model.py", line 102, in __init__
    super().__init__(args, transformer=transformer, parallel_output=parallel_output, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sat/model/official/llama_model.py", line 101, in __init__
    super().__init__(args, transformer=transformer, parallel_output=parallel_output, layernorm=layernorm, activation_func=activation_func, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sat/model/base_model.py", line 88, in __init__
    success = _simple_init(model_parallel_size=args.model_parallel_size)
  File "/usr/local/lib/python3.10/dist-packages/sat/arguments.py", line 308, in _simple_init
    if initialize_distributed(args): # first time init model parallel, print warning
  File "/usr/local/lib/python3.10/dist-packages/sat/arguments.py", line 511, in initialize_distributed
    torch.distributed.init_process_group(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1148, in init_process_group
    default_pg, _ = _new_process_group_helper(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1279, in _new_process_group_helper
    backend_class = ProcessGroupNCCL(backend_prefix_store, group_rank, group_size, pg_options)
RuntimeError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!
```
You can try just running https://colab.research.google.com/drive/1xNTJJh94_6xL3pAszLuCVDsJ0x030uB4?usp=sharing and can see it. Very eager to run this on cpu. Kindly fix if you have bandwidth!

**Comment by 1049451037** [comment]
You should use the latest version of sat.

```
git clone https://github.com/THUDM/SwissArmyTransformer
cd SwissArmyTransformer
pip install .
```
