### ISSUE TITLE
Fine Tuning Issue with scripts/finetune_224_lora.sh

### ISSUE THREAD

**Issue by signalprime** [THUDM/CogVLM#89]
Following the example from README.md, `scripts/finetune_490_lora.sh` works, but `scripts/finetune_224_lora.sh` returns the following error:
```
NCCL_DEBUG=info NCCL_IB_DISABLE=0 NCCL_NET_GDR_LEVEL=2 LOCAL_WORLD_SIZE=8 SAT_HOME=~/.sat_models deepspeed --master_port 16666 --hostfile hostfile finetune_demo.py --experiment-name finetune-cogvlm-base-224 --model-parallel-size 4 --mode finetune --train-iters 800 --resume-dataloader --from_pretrained cogvlm-base-224 --max_length 319 --lora_rank 10 --use_lora --local_tokenizer lmsys/vicuna-7b-v1.5 --version base --train-data ./archive_split/train --valid-data ./archive_split/valid --distributed-backend nccl --lr-decay-style cosine --warmup .02 --checkpoint-activations --vit_checkpoint_activations --save-interval 200 --eval-interval 200 --save ./checkpoints --eval-iters 10 --eval-batch-size 1 --split 1. --deepspeed_config scripts/test_config_bf16.json --skip-init --seed 2023
[2023-11-11 02:29:38,510] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-11-11 02:29:41,080] [WARNING] [runner.py:203:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2023-11-11 02:29:41,086] [INFO] [runner.py:570:main] cmd = /usr/bin/python3 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=16666 --enable_each_rank_log=None finetune_demo.py --experiment-name finetune-cogvlm-base-224 --model-parallel-size 4 --mode finetune --train-iters 800 --resume-dataloader --from_pretrained cogvlm-base-224 --max_length 319 --lora_rank 10 --use_lora --local_tokenizer lmsys/vicuna-7b-v1.5 --version base --train-data ./archive_split/train --valid-data ./archive_split/valid --distributed-backend nccl --lr-decay-style cosine --warmup .02 --checkpoint-activations --vit_checkpoint_activations --save-interval 200 --eval-interval 200 --save ./checkpoints --eval-iters 10 --eval-batch-size 1 --split 1. --deepspeed_config scripts/test_config_bf16.json --skip-init --seed 2023
[2023-11-11 02:29:43,408] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-11-11 02:29:45,196] [INFO] [launch.py:138:main] 0 NCCL_IB_DISABLE=0
[2023-11-11 02:29:45,196] [INFO] [launch.py:138:main] 0 NCCL_DEBUG=info
[2023-11-11 02:29:45,196] [INFO] [launch.py:138:main] 0 NCCL_NET_GDR_LEVEL=2
[2023-11-11 02:29:45,196] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE=libnccl-dev=2.15.5-1+cuda11.8
[2023-11-11 02:29:45,196] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE_VERSION=2.15.5-1
[2023-11-11 02:29:45,196] [INFO] [launch.py:138:main] 0 NCCL_VERSION=2.15.5-1
[2023-11-11 02:29:45,197] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE_NAME=libnccl-dev
[2023-11-11 02:29:45,197] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE=libnccl2=2.15.5-1+cuda11.8
[2023-11-11 02:29:45,197] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE_NAME=libnccl2
[2023-11-11 02:29:45,197] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE_VERSION=2.15.5-1
[2023-11-11 02:29:45,197] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0]}
[2023-11-11 02:29:45,197] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=1, node_rank=0
[2023-11-11 02:29:45,197] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2023-11-11 02:29:45,197] [INFO] [launch.py:163:main] dist_world_size=1
[2023-11-11 02:29:45,197] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0
[2023-11-11 02:29:47,566] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-11-11 02:29:50,970] [INFO] using world size: 1 and model-parallel size: 4 
[2023-11-11 02:29:50,970] [INFO] > padded vocab (size: 100) with 28 dummy tokens (new size: 128)
[2023-11-11 02:29:50,970] [INFO] Will override arguments with manually specified deepspeed_config!
[2023-11-11 02:29:50,975] [INFO] [RANK 0] > initializing model parallel with size 4
[2023-11-11 02:29:50,975] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-11-11 02:29:50,976] [INFO] [checkpointing.py:1032:_configure_using_config_file] {'partition_activations': False, 'contiguous_memory_optimization': False, 'cpu_checkpointing': False, 'number_checkpoints': None, 'synchronize_checkpoint_boundary': False, 'profile': False}
[2023-11-11 02:29:50,977] [INFO] [checkpointing.py:227:model_parallel_cuda_manual_seed] > initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 4741 and data parallel seed: 2023
Downloading models r2://cogvlm-base-224.zip into /root/.sat_models ...
/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'c8a00746a80e06c4632028e37de24d6e.r2.cloudflarestorage.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++100.0% 28.0 GB / 28.0 GB     
Unzipping /root/.sat_models/cogvlm-base-224.zip...
[2023-11-11 02:36:44,861] [INFO] [RANK 0] building FineTuneTrainCogVLMModel model ...
Traceback (most recent call last):
  File "/content/CogVLM/finetune_demo.py", line 239, in <module>
    model, args = FineTuneTrainCogVLMModel.from_pretrained(args.from_pretrained, args, overwrite_args={'model_parallel_size': args.model_parallel_size} if args.model_parallel_size != 1 else {})
  File "/usr/local/lib/python3.10/dist-packages/sat/model/base_model.py", line 219, in from_pretrained
    model, model_args = cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=True, overwrite_args=overwrite_args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sat/model/base_model.py", line 207, in from_pretrained_base
    model = get_model(args, cls, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sat/model/base_model.py", line 379, in get_model
    model = model_cls(args, params_dtype=params_dtype, **kwargs)
  File "/content/CogVLM/models/cogvlm_model.py", line 125, in __init__
    super().__init__(args, transformer=transformer, parallel_output=parallel_output, **kw_args)
  File "/content/CogVLM/models/cogvlm_model.py", line 102, in __init__
    super().__init__(args, transformer=transformer, parallel_output=parallel_output, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sat/model/official/llama_model.py", line 101, in __init__
    super().__init__(args, transformer=transformer, parallel_output=parallel_output, layernorm=layernorm, activation_func=activation_func, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sat/model/base_model.py", line 88, in __init__
    success = _simple_init(model_parallel_size=args.model_parallel_size)
  File "/usr/local/lib/python3.10/dist-packages/sat/arguments.py", line 308, in _simple_init
    if initialize_distributed(args): # first time init model parallel, print warning
  File "/usr/local/lib/python3.10/dist-packages/sat/arguments.py", line 486, in initialize_distributed
    raise ValueError('model_parallel_size is inconsistent with prior configuration.'
ValueError: model_parallel_size is inconsistent with prior configuration.We currently do not support changing model_parallel_size.
[2023-11-11 02:36:46,630] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 3988
[2023-11-11 02:36:46,630] [ERROR] [launch.py:321:sigkill_handler] ['/usr/bin/python3', '-u', 'finetune_demo.py', '--local_rank=0', '--experiment-name', 'finetune-cogvlm-base-224', '--model-parallel-size', '4', '--mode', 'finetune', '--train-iters', '800', '--resume-dataloader', '--from_pretrained', 'cogvlm-base-224', '--max_length', '319', '--lora_rank', '10', '--use_lora', '--local_tokenizer', 'lmsys/vicuna-7b-v1.5', '--version', 'base', '--train-data', './archive_split/train', '--valid-data', './archive_split/valid', '--distributed-backend', 'nccl', '--lr-decay-style', 'cosine', '--warmup', '.02', '--checkpoint-activations', '--vit_checkpoint_activations', '--save-interval', '200', '--eval-interval', '200', '--save', './checkpoints', '--eval-iters', '10', '--eval-batch-size', '1', '--split', '1.', '--deepspeed_config', 'scripts/test_config_bf16.json', '--skip-init', '--seed', '2023'] exits with return code = 1
```

Is the error `ValueError: model_parallel_size is inconsistent with prior configuration.We currently do not support changing model_parallel_size.` familiar or easy to solve?

Thanks!

**Comment by 1049451037** [comment]
As in your posted content, you are using world size: 1 and model-parallel size: 4. It's not possible to fine-tune with just 1 GPU (world_size=1).

**Comment by signalprime** [comment]
Thank you @1049451037
