### ISSUE TITLE
multi gpu CLI 推理错误

### ISSUE THREAD

**Issue by liuzhx2016** [THUDM/CogVLM#92]
您好，我使用多卡进行模型的推理，命令如下
torchrun --standalone --nnodes=1 --nproc-per-node=4 cli_demo.py --from_pretrained /home/data/data_main/model/cogvlm-chat --version chat --english --bf16 --local_tokenizer /home/data/data_main/model/vicuna-7b-v1.5
但是出现了错误，截图如下，请问是什么原因，谢谢

Traceback (most recent call last):
  File "cli_demo.py", line 154, in <module>
    main()
  File "cli_demo.py", line 52, in main
    tokenizer = llama2_tokenizer(args.local_tokenizer, signal_type=args.version)
  File "/home/data/data_main/CogVLM/utils/language.py", line 22, in llama2_tokenizer
    tokenizer.pad_token_id = 32000
  File "/home/main/anaconda3/envs/chat_new/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1267, in pad_token_id
    self._pad_token = self.convert_ids_to_tokens(value) if value is not None else None
  File "/home/main/anaconda3/envs/chat_new/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 973, in convert_ids_to_tokens
    return self._convert_id_to_token(ids)
  File "/home/main/anaconda3/envs/chat_new/lib/python3.8/site-packages/transformers/models/llama/tokenization_llama.py", line 280, in _convert_id_to_token
    token = self.sp_model.IdToPiece(index)
  File "/home/main/anaconda3/envs/chat_new/lib/python3.8/site-packages/sentencepiece/__init__.py", line 1045, in _batched_func
    return _func(self, arg)
  File "/home/main/anaconda3/envs/chat_new/lib/python3.8/site-packages/sentencepiece/__init__.py", line 1038, in _func
    raise IndexError('piece id is out of range.')
IndexError: piece id is out of range.

**Comment by 1049451037** [comment]
cc @mactavish91 

Is this tokenizer updated?
