### ISSUE TITLE
Help in running

### ISSUE THREAD

**Issue by akshat-khare** [THUDM/CogVLM#99]
I tried running it on Jarvislabs with 2 A100 40 gb. Its failing. Do you have some container I can run the readme steps on? Its mostly seemingly driver issues with versions you are having. I have tried it on colab too but faced issues pertaining to compute capability. Could someone please guide me on how and where to run this? Tried many things but failed. A docker would be very useful!
```
[2023-11-15 22:14:04,146] torch.distributed.run: [WARNING] master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
/opt/conda/lib/python3.10/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11080). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org/ to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
[2023-11-15 22:14:05,747] [INFO] DeepSpeed/CUDA is not installed, fallback to Pytorch checkpointing.
[2023-11-15 22:14:06,655] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-11-15 22:14:08,111] [WARNING] Failed to load bitsandbytes:No module named 'bitsandbytes'
Exception ignored in: <function BaseFileLock.__del__ at 0x7f7b55a3e440>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/filelock/_api.py", line 240, in __del__
    self.release(force=True)
  File "/opt/conda/lib/python3.10/site-packages/filelock/_api.py", line 201, in release
    with self._thread_lock:
AttributeError: 'UnixFileLock' object has no attribute '_thread_lock'
Traceback (most recent call last):
  File "/home/CogVLM/cli_demo.py", line 154, in <module>
    main()
  File "/home/CogVLM/cli_demo.py", line 34, in main
    model, model_args = CogVLMModel.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/sat/model/base_model.py", line 215, in from_pretrained
    return cls.from_pretrained_base(name, args=args, home_path=home_path, url=url, prefix=prefix, build_only=build_only, overwrite_args=overwrite_args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/sat/model/base_model.py", line 201, in from_pretrained_base
    model_path = auto_create(name, path=home_path, url=url)
  File "/opt/conda/lib/python3.10/site-packages/sat/resources/download.py", line 50, in auto_create
    lock = FileLock(model_path + '.lock', mode=0o777)
TypeError: BaseFileLock.__init__() got an unexpected keyword argument 'mode'
[2023-11-15 22:14:09,444] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 300) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
cli_demo.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-15_22:14:09
  host      : 79d1120d0b97
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 300)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
  ```

**Comment by 1049451037** [comment]
```
pip install -U filelock
```

**Comment by akshat-khare** [comment]
```
root@c38df2277638:~# torchrun --standalone --nnodes=2 --nproc-per-node=2 cli_demo.py --from_pretrained cogvlm-chat --version chat --english --bf16
[2023-11-17 12:00:08,785] torch.distributed.run: [WARNING] master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
[2023-11-17 12:00:08,785] torch.distributed.run: [WARNING] 
[2023-11-17 12:00:08,785] torch.distributed.run: [WARNING] *****************************************
[2023-11-17 12:00:08,785] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2023-11-17 12:00:08,785] torch.distributed.run: [WARNING] *****************************************
```
It is taking forever after this. Am I missing something?

**Comment by MaxGonzalezSaez-Diez** [comment]
Similar issue here

**Comment by akshat-khare** [comment]
@1049451037 Please consider creating a dockerfile. I most dearly wish to use this and learn but currently am inhibited by the issues. I am happy to even jump on a call or collaborate to create the dockerfile. Please help!

**Comment by 1049451037** [comment]
`torchrun --standalone --nnodes=2 --nproc-per-node=2` means you have two machines, each having 2 cards. If you only have one machine with 2 cards, just set `nnodes=1`.

**Comment by 1049451037** [comment]
Now, you can also try the huggingface version: https://huggingface.co/THUDM/cogvlm-chat-hf
